---
title: "Artículos en prensa^[Los siguientes artículos han sido aceptados para publicación en la Revista UniNorte de Medicina y Ciencias de la Salud, y se encuentran actualmente en proceso de edición y formateo.]"
output:
    html_document:
        toc: false
---

# Tabla de contenidos
## Nutrición
- **Contaminación bacteriana de esponja de lavado y bachas de cocina de escuelas y colegios de Asunción y alrededores**  
Clyde Cowan, Tania León, Dora Pereira, Noemí Zárate  
<a href="javascript:unhide('v07_01a01res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_01a01res" class="hidden">
En la mayoría de los casos, las principales intoxicaciones alimentarias que se originan en las cocinas son por una mala higiene. El objetivo fue demostrar la contaminación microbiana de esponjas de lavado y bachas de cocina, de 11 escuelas y colegios de Asunción y alrededores, mediante estudios microbiológicos El estudio fue descriptivo analítico transverso. Se han tomado muestras de esponjas de lavado y de hisopado de bachas de cocina. De las muestras de esponjas obtenidas en 11 escuelas, 10 presentaron una alta contaminación con bacterias aerobias mesófilas, y coliformes fecales y solo 1 fue estéril. De los hisopados de bachas de 11 escuelas, 9 presentaron una alta contaminación con bacterias aerobias mesófilas y coliformes fecales 1 moderda contaminación y 1 fue estéril. En ningún caso se aisló bacterias causantes de toxiinfección alimentaria. CONCLUSIÓN: Las esponjas y bachas estudiadas se hallan altamente contaminadas tal como lo publican en otros trabajos realizados En el Paraguay no existen publicaciones respecto a la contaminación de estos elementos de cocina.
</div>

- **Percepción materna del estado nutricional y de la ingesta alimentaria de niños de 2 a 5 años**  
Álvaro Andrés Andrada Duarte, María Luján Otazú Benavente  
<a href="javascript:unhide('v07_01a02res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_01a02res" class="hidden">
La percepción materna respecto al estado nutricional podría restar importancia a diversos cuidados particulares enfocados a la malnutrición infantil e incluso afectar la alimentación. Con el objetivo de evaluarla relación que entre la percepción materna sobre el estado nutricional de sus hijos y el estado real de los mismos en niños de 3 a 5 años que acudieron al Centro de Salud N° 9 en octubre de 2016, se realizó un estudio observacional analítico de corte transverso. La muestra estuvo conformada por 30 niños, de los cuales, el 57% corresponde al sexo femenino, el 53% son de 2 a 3 años. El 63% presenta una relación P/E adecuada, el 20% algún grado de sobrepeso y el 17% riesgo de desnutrición. El 93% presenta una talla adecuada para la edad, el 3% riesgo de talla baja y el 3% talla baja. Presentan inadecuados hábitos alimentarios en relación al cumplimiento de las recomendaciones del consumo de lácteos, carnes, verduras, frutas, y tiene un alto consumo de azúcar. Hubo una buena concordancia entre la percepción de las madres y el estado nutricional de sus hijos con peso normal (97%), pero se observó una distorsión cuando los niños presentaban exceso de peso, ya que ninguna madre consideró a su hijo con sobrepeso (0%) y sólo el 3% los percibió con déficit de peso. Conclusión: En los casos de niños con malnutrición existe una distorsión en la apreciación de las madres con respecto al estado nutricional de sus hijos, sobre todo en el exceso de peso y sobre el déficit, el cual es subestimado.
</div>

- **Manejo nutricional en recién nacidos prematuros en dos hospitales materno-infantiles**  
Fátima Monserrat Ibarra Dos Santos  
<a href="javascript:unhide('v07_01a03res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_01a03res" class="hidden">
El nacimiento pretérmino es una emergencia nutricional y requiere consideraciones especiales constituye un desafío desde el nacimiento y hasta bien avanzada la infancia. Uno de los mayores retos es mantener una ganancia de peso similar al crecimiento fetal hasta que el neonato alcance las 40 semanas de edad postconcepcional, y luego lograr un crecimiento que garantice eventualmente, una talla acorde a la edad cronológica y un óptimo neurodesarrollo. Todas las metas se pueden alcanzar con el inicio precoz de la alimentación enteral, incluso una alimentación trófica, y el adecuado seguimiento de las variables antropométricas y bioquímicas que evidencian un crecimiento saludable. Se propuso evaluar el manejo nutricional en recién nacidos prematuros y factores maternos. Se analizó 23 fichas del hospital Materno Infantil San Pablo y de 23 fichas del hospital Materno Infantil Barrio Obrero. Obteniendo un total de 46 fichas clínicas estudiadas. De los cuales, el 65% del Hospital Barrio Obrero y 74% del Hospital San Pablo corresponde al sexo masculino, en cuanto al rango de edad predominante es de 34 a <37 semanas con el 87% correspondiente al Hospital Barrio Obrero y 78% del Hospital San Pablo.
</div>

- **Estado nutricional en embarazadas adolescentes y sus complicaciones**  
Magalí Mujica Burguéz, Gabriela Tamara Tironi Soljancic  
<a href="javascript:unhide('v07_01a04res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_01a04res" class="hidden">
El embarazo en adolescentes puede tener consecuencias adversas para la salud. Por eso se realizó este estudio con el objetivo de determinar el estado nutricional en embarazadas adolescentes y sus complicaciones realizadas en el hospital de la Cruz Roja y el hospital de Barrio Obrero en setiembre de 2016, se diseñó un estudio observacional descriptivo de corte transversal. La muestra estuvo conformada por 33 embarazadas, de las cuales, el 82 % corresponde en edades entre los 18 a 19 años. El 33% de las embarazadas presentan desnutrición, un 30% con peso normal, el 21% con exceso de peso y el 12% con obesidad En las patologías diagnosticada durante el embarazo refleja un 58% anemia, el 42% presenta infección en las vías urinarias, un 9% indica presión alta, el 15% indica diabetes gestacional, un 6% indica presión baja y un 6% indica deshidratación. Podemos observar que el gran número de patologías diagnosticadas se ven o se manifiestan durante el embarazo, con un buen control prenatal estas patologías pueden ser tratadas.
</div>

\   

## Fisioterapia y Kinesiología
- **Características de ingreso y tratamiento kinésico en pacientes adultos post operados de revascularización quirúrgica coronaria en la Unidad de Ciudados Intensivos del Instituto Nacional de Cardiología "San Jorge"**  
Jerson Daniel Romero Morínigo  
<a href="javascript:unhide('v07_01a05res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_01a05res" class="hidden">
Propósito:  Identificar  las  características  clínicas  de  ingreso  y  el tratamiento kinésico de los pacientes post-operados de revascularización quirúrgica coronaria del Instituto de Cardiología San Jorge. Metodología: La investigación se realizó en las instalaciones del Instituto de Cardiología San Jorge luego de la aprobación de parte de la institución, la recolección de datos se realizó dentro de la terapia intensiva para recolectar los datos  registrados  en  las  fichas  clínicas  de los  pacientes  de ambos  sexos  que ingresaron a la Unidad de Cuidados Intensivos post-operado de revascularización quirúrgica coronaria durante el periodo de Marzo a Diciembre del 2016. Resultados: La muestra fue conformada por personas de ambos sexos siendo el porcentaje para el sexo masculino del 75% y para el sexo femenino del 25%, con edad máxima de 74 ±59,86 años y edad mínima de 45 años en sujetos de ambos sexos.Los valores promedios y desviación estándar de los signos vitales tras el ingreso de los pacientes fueron los siguientes: presión arterial sistólica 108.67 ± 24.08 con un pico máximo de 165 mmHg y un pico mínimo de 60 mmHg, presión arterial diastólica 64.53 ± 14.82, con un valor máximo de 95 mmHg y valor mínimo de 30 mmHg, la frecuencia cardiaca 83.97 ± 13.20, con un valor máximo de 128 lpm y un valor mínimo de 60 lpm. Conclusiones: Se registró 36 pacientes de ambos sexos con edades de 45 a 74 años de edad ingresados a UCI-A, donde se encontró mayor incidencia para el sexo masculino dando un porcentaje de 75% y menor incidencia para el sexo femenino  conun  porcentaje de 25%. Es importante considerar dentro  de las características de ingreso de los pacientes adultos en UCI-A la rehabilitación cardiaca en conjunto con la kinesiterapia respiratoria ayudan al paciente con técnicas respiratorias o la utilización de inspirómetros con el fin de aumentar los volúmenes respiratorios y fácil eliminación de secreciones y así mejorar la respiración del paciente, si es necesario la técnica de aspiración de secreciones.
</div>

- **Características de la rehabilitación kinésica en pacientes post quirúrgicos cardiovasculares enfocada al reacondicionamiento físico**  
Raquel Rodriguez Cardozo  
<a href="javascript:unhide('v07_02a01res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_02a01res" class="hidden">
Propósito: Identificar los efectos de la aplicación de un protocolo de rehabilitación kinésica en la condición física de los pacientes post operados cardiovasculares del Instituto Nacional de Cardiología, Hospital Militar San Jorge. Metodología: El trabajo se realizó en el hospital San Jorge, donde se evaluaron a aquellos pacientes post operados cardiovasculares.  Se obtuvieron monitorizaciones de los signos vitales de cada paciente antes, durante y después de realizar sus actividades físicas. Se aplicó la de Escala de Borg que tiene por objetivo medir el esfuerzo del individuo al realizar ejercicios. Resultados: En el Protocolo de Rehabilitación Kinésica en pacientes postquirúrgicos cardiovasculares realizado en el Hospital Militar San Jorge, se pudo observar que el 60% de la población estuvo conformado por hombres y el 40% por mujeres, con edad de 43 años y máxima 71 años para ambos sexos. Donde los días de internación variaron: 15 días de internación en un 10%, 12 días 30%,  6 y 3 días en un 30%. Conclusiones: Se obtuvo resultados positivos mediante la aplicación del protocolo de rehabilitación kinésica, donde los pacientes lograron mejorar su tolerancia a las actividades físicas y también sus signos vitales (Frecuencia Cardiaca, Frecuencia Respiratoria, PAM y Saturación), sin que ellos refieran alguna incapacidad o negación a las mismas.
</div>

- **Relación entre diagnóstico de ingreso, permanencia en asistencia respiratoria mecánica y el proceso de desconexión de pacientes críticos en la Unidad de Cuidados Intensivos del Hospital Nacional de Itauguá**  
Ricardo Neuman González  
<a href="javascript:unhide('v07_02a02res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_02a02res" class="hidden">
Propósito: Establecer la relación existente entre el proceso de desconexión de Asistencia Respiratoria Mecánica en comparación al diagnóstico de ingresos UCI y los días de permanencia en ARM. Metodología: La investigación se realizó en las instalaciones del Hospital Nacional de Itauguá (HNI) posterior aprobación por parte de la institución, dichas visitas se realizarán en el Departamento de Estadísticas para recolectar los datos de los pacientes de ambos sexos que hayan ingresado a la unidad de cuidados intensivos (UCI) durante el mes de diciembre del 2014 y enero del 2015. Resultados: Cohorte 1: Pacientes de ambos sexos que ingresaron a la unidad de cuidados intensivos con Asistencia Respiratoria Mecánica, de etiología no traumática. Conforman un total de 59 pacientes de ambos sexos, representando un 77.63% de la muestra. Presentó una tasa de mortalidad del 96,6 %. El proceso de destete se llevó a cabo en el 100% de la muestra y tuvo un fallo del 94,74% (57 pacientes) y un éxito en tan solo el 3,95% (2 pacientes) de la muestra. Cohorte 2: Pacientes de ambos sexos que ingresaron a la unidad de cuidados intensivos con Asistencia Respiratoria Mecánica, de etiología traumática. Conforman un total de 17 pacientes de ambos sexos, representando un 22,37% de la muestra. Presentó una tasa de mortalidad del 100%. Y la falla del destete se evidencio así mismo en el 100% de los casos. Se registraron valores similares de signos vitales en el ingreso – egreso de estos pacientes. Así como también en el promedio de días de internación de los mismos y la modalidad ventilatoria en la que iniciaron el procedimiento en la unidad de cuidados intensivos. Conclusión: En los procesos fallidos de desconexión identificados durante el presente estudio, nos indican que no existe una relación entre el diagnóstico de ingreso y los días de permanencia en A.R.M. en ninguno de las cohortes analizados esto es debido a la nula utilización o el desconocimiento de los parámetros válidos para efectuar un protocolo de destete con el menor riesgo posible, por parte de los profesionales de la salud.
</div>

- **Valoración postural y hábitos ergonómicos en cirujanos oftalmólogos de Fundación Visión**  
Randall Javier Chaparro Bontrager  
<a href="javascript:unhide('v07_02a03res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_02a03res" class="hidden">
Propósito: la meta principal del estudio consiste en identificar las principales alteraciones posturales de los médicos cirujanos oftalmólogos de la Fundación Visión Paraguay. Metodología: El trabajo se realizara en Fundación Vision, donde se realizara una encuesta a los Tutores Oftalmólogos y Residentes en oftalmología de 2do y 3er año.  La encuesta fue realizada a los profesionales que realizan las intervenciones quirúrgicas dentro de la Fundación Vision. Resultados: El 86% de los encuestados refirió la necesidad de adoptar posturas especiales por largo tiempo para los procedimientos quirúrgicos y el 14% no refirió ninguna necesidad de adoptar posturas especiales. El 57% de los encuestados refirió padecer una patología musculoesqueletica preexistente o subyacente y el 43% no refirió ninguna patología. Conclusión: En el presente estudio el personal medico quirúrgico menciono como principal sintomatología el dolor, cabe mencionar que mas del 80% refirió algún tipo de molestia en los últimos 7 dias.
</div>

- **Calidad de vida en pacientes con enfermedad de Parkinson que reciben tratamiento kinésico vs. pacientes que no reciben tratamiento con la Escala PDQ-39 en el Departamento Central en enero de 2017**  
Margareth Armoa Sánchez  
<a href="javascript:unhide('v07_02a04res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_02a04res" class="hidden">
Propósito: la meta principal del estudio consiste en comparar el nivel de Calidad de Vida entre los pacientes con Enfermedad de Parkinson que reciben y los que no reciben tratamiento kinésico a través de la Escala PDQ-39 (Parkinson’s Disease Questionnaire) en el Departamento Central en enero del año 2017. Metodología: Se aplicó las Escalas de Hoehn y Yahr y el Cuestionario para la enfermedad de Parkinson (Parkinson’s Disease Questionnaire, PDQ-39), a 10 pacientes geriátricos que reciben tratamiento kinésico y a 10 pacientes que no reciben tratamiento kinésico, y posteriormente se analizaron los resultados obtenidos en ambas evaluaciones. Resultados: En lo que respecta con el puntaje total obtenido en razón a porcentaje del Cuestionario PDQ-39, se puede observar en cuanto al grupo que realiza tratamiento que un 30% de la muestra tiene un grado de discapacidad pon encima del 60%, alcanzando valores del 62.82, 73.08 y 76.92%; el 70% restante posee grados de discapacidad que fluctúan entre 43.59 y 12.18%. Conclusión: En el presente trabajo, la diferencia encontrada en cuanto al porcentaje de Calidad de Vida en los pacientes que no realizan ningún tratamiento kinésico resultó mejor en comparación a los que realizan tratamiento kinésico. Esto se evidenció mediante la Escala PDQ-39 en pacientes geriátricos en el área Central.
</div>

- **Efectos del uso del espirómetro incentivo VOLDYNE(R) vs TRIFLOW(R) en pacientes post operados de cirugía cardiovascular en el área de UCIA del Instituto Nacional de Cardiología**  
Adriana Raquel Portillo Zarza  
<a href="javascript:unhide('v07_02a04res');">[Resumen]</a>
<a onClick="inPress()">[Texto completo]</a>

<div id="v07_02a04res" class="hidden">
Propósito: Comparar la eficacia de los espirómetros incentivos de volumen llamado Voldyne® vs de flujo, el Triflow® sobre el volumen tidal y la presión inspiratoria máxima en los pacientes post operados de cirugía cardiovascular. Metodología: El trabajo se realizó en las inmediaciones del Hospital Militar San Jorge en el área de Unidad de Terapia Intensiva Adultos, se evaluaron a pacientes adultos post operados de cirugía cardiovascular. Se registraron los datos de los pacientes antes, y después de la implementación de ambas técnicas, Voldyne® y Triflow® en las dos cohortes. Resultados: Mediante la variación se observó por la prueba de student que entre los valores de la PIMAX inicial y final del grupo Voldyne®, se obtuvo un resultado de 0,018. Mediante la variación se observó por la prueba de student que entre los valores de la PIMAX inicial y final del grupo Triflow®, se obtuvo un resultado de 0,005. Se analizó los valores de la PIMAX incial y final en el grupo Triflow®, en el inicio el mínimo fue de -10 y el máximo fue de –25 en cambio los parámetros finales fue un minimo de –27 y el máximo de –40. Conclusión: En lo que concierne la diferencia fue que el Voldyne®, en el Volumen Tidal fue mayormente demostrativo en lo que respecta al Triflow®. Esto significa que el Voldyne® es mayormente ventajoso en pacientes con problemas restrictivas por la disminución de expansión pulmonar. Por el contrario, el Triflow® fue mayormente significativamente en la PIMAX en relación al Voldyne®. Por ello este tipo de Espirómetro es más beneficioso en los pacientes con enfermedades obstructivas.
</div>
