---
title: "Grado de conocimiento y uso del idioma guaraní de estudiantes en la interrelación con usuarios guaraní hablantes, Instituto Dr. Andrés Barbero, 2012"
author: "Aida Lucía Maidana de Zarza^[Facultad de Medicina, Universidad del Norte]"
---

```{r echo=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, fig.align="center")
library(ggplot2)
```

# Resumen
Se realizó en el Instituto "Dr. Andrés Barbero" Casa Central, cuyo objetivo fue evaluar el grado de conocimiento y uso del idioma guaraní de los estudiantes de las carreras de Enfermería y de Obstetricia. Observacional descriptivo con componente analítico. Universo constituido por 609 estudiantes. Muestra: 334 (54%) estudiantes. Muestreo no probabilístico de casos consecutivos. Se utilizó un cuestionario con preguntas cerradas y abiertas. Los hallazgos más relevantes fueron: Estudiantes mayoritariamente  de sexo femenino, 21 a 24 años de edad,  estado civil soltero/a, de la carrera de Enfermería y provenientes del Gran Asunción. Según  la percepción del dominio que poseen sobre el idioma guaraní  es  Bueno. La  interpretación que realizan los estudiantes del idioma guaraní en la comunicación con el usuario guaraní hablante a través de la traducción de oraciones es Aceptable. El idioma es necesario para el entendimiento entre  usuario guaraní hablante y  prestador de salud, es una estrategia útil para la Salud Pública. Mayoritariamente consideraron imperiosa la inclusión del idioma guaraní en la malla curricular. Al relacionar escolaridad y uso del idioma, independientemente del año cursado y carrera, una minoría usa mucho el idioma guaraní en su interrelación comunicacional. Relacionado la procedencia y el dominio del idioma guaraní se encuentra una minoría de estudiantes provenientes de Asunción y Gran Asunción con dominio entre Excelente y Muy Bueno,  contra estudiantes provenientes de otras localidades con una $P<0.00001$, muy significativo,  por el origen de los estudiantes. Con lo que se concluye que el grado de conocimiento del idioma guaraní de los estudiantes de las carreras de Enfermería y de Obstetricia del Instituto Dr. Andrés Barbero, Casa Central es Aceptable y el uso  Deficiente en la interrelación con el usuario guaraní hablante. 

\   

# Introducción
El guaraní, idioma enigmático, modelo intangible de la cultura guaraní y paraguaya, hablado en la actualidad por la mayoría de la población del Paraguay,  más que nunca en nuestro tiempo es una necesidad, y en especial en las carreras de Enfermería y de Obstetricia, teniendo en cuenta que la población que acude a los servicios de salud, ya sea hospital de alta complejidad, Puesto de Salud  o a las unidades de Salud Familiar (USF) de la Estrategia Atención Primaria de Salud (APS), representa una parte del 37% de la población monolingüe guaraní hablante siendo el área de atención, el  punto de encuentro con los prestadores de salud.

Con la implementación de la Estrategia APS, el estado busca ofrecer atención de salud de calidad a los compatriotas, instalándose las Unidades de Salud Familiar (USF) en las distintas  comunidades del país, de manera a estar más cerca de la gente y  realizar promociones  de la salud y prevención de las enfermedades. Pero este nuevo paradigma requiere de  prestadores de salud competentes, que tengan  conocimiento y dominio de ambos idiomas, tanto el  guaraní como el castellano de manera a hacer efectiva  y acompañar los esfuerzos del Estado Paraguayo. 
 	La comunicación es un  fenómeno  que posibilita el relacionamiento con las demás personas. Por otro lado, el idioma representa dentro de una comunidad cultural una cosmogonía única y diferente de la que ofrece otros idiomas; de ahí su importancia a la hora de entender la inteligencia, la afectividad de un interlocutor. Al guaraní, como idioma, lo sentimos así en nuestro trato diario, y especialmente cuando queremos cerrar un contrato personal o social. 

Al conocer, entender y comprender las  costumbres y tradiciones del pueblo, se está superando una brecha comunicacional, facilitando de esa manera la comprensión del usuario guaraní hablante del mensaje recibido relacionado a la promoción y prevención.

La Agencia Nacional de Evaluación y Acreditación de la Educación superior, ANEAES, dentro de los criterios de calidad de la Carrera de enfermería parte 5, enfatiza que la competencia de comunicarse en los idiomas oficiales, el guaraní y el castellano,  debe ser desarrollada a través de la capacidad de comunicarse de forma oral y escrita en el entorno profesional con usuarios, pares, personal auxiliar, empleadores y la comunidad toda. 

Según las Naciones Unidas, educar a los niños de las minorías indígenas o de tribus exclusivamente en el idioma de la cultura dominante, en lugar de hacerlo en su lengua materna, perpetúa la pobreza. Existe la necesidad de reconocer nuestra condición de país multicultural y actuar en consonancia con ello. La brecha de la pobreza y la brecha del idioma son caras de la misma moneda. 

La prohibición del uso del idioma guaraní viene más allá de la  época de don Carlos Antonio López. Esta situación se ha extendido hasta el último régimen dictatorial vivido dos décadas atrás en nuestro país, considerándose "guarango/a" o "grosero" al que hablara en guaraní. Recién en el año 1992 con la Reforma Constitucional en sus artículos 77 y 140, incluye al idioma guaraní como idioma oficial, contando nuestro país desde entonces con dos lenguas oficiales, el guaraní y el castellano.

A partir de allí se inicia tímidamente la inclusión de la enseñanza en el diseño curricular, de la Educación escolar básica, pero con docentes que en su mayoría, no se identificaban con la misma y asumía la cátedra por no perder sus rubros o como una oportunidad para incursionar en la enseñanza. Muchos de estos docentes sin una didáctica motivadora y armonizante para la enseñanza del idioma guaraní, y por ende, carente de atractivo y significancia para los niños/as, lograron que los mismos odiaran dicha lengua y se levantaran airadas protestas de los padres a fin de lograr nuevamente la eliminación del  idioma guaraní del curriculum escolar.

Durante la práctica profesional de los estudiantes de enfermería del Instituto Dr. Andrés Barbero (IAB), se pudo constatar la dificultad que los jóvenes manifiestan  a la hora de comunicarse  con el usuario guaraní hablante. Hoy día, los que logran una comunicación eficaz con el usuario guaraní hablante son en su mayoría provenientes del interior.

En más de una ocasión los usuarios enseñaban a los jóvenes la manera correcta de preguntar o pronunciar las palabras. Este hecho lleva a una falta de entendimiento entre usuario y estudiante; vergüenza para hablar en guaraní por temor a pronunciarlo mal y ser motivo de burla, inseguridad al expresarse, además del concepto erróneo del bajo status social de idioma guaraní, entre otros.

El objetivo del trabajo de investigación es evaluar el grado de conocimiento y el uso del idioma guaraní en  los estudiantes de las carreras de  Enfermería  y de Obstetricia  en  la interrelación con el  usuario guaraní hablante. 

Los objetivos específicos son establecer el uso del idioma desde la percepción  del/a  estudiante, determinar el conocimiento y el dominio del idioma guaraní de  los estudiantes  en la comunicación con el usuario a través de la traducción de palabras y oraciones, examinar la actitud de los estudiantes respecto  a la inclusión del idioma guaraní dentro de la malla curricular,   y relacionar el uso del idioma guaraní con la escolaridad de los estudiantes;  y  procedencia  de estudiantes y dominio del idioma guaraní.

Esta constatación lleva a la autora a formular la siguiente pregunta de investigación: ¿Cuál es grado de conocimiento y  uso del idioma guaraní de los estudiantes de las carreras de Enfermería y de Obstetricia en su interrelación con el usuario guaraní hablante?

Los datos obtenidos se pondrán a consideración de las autoridades de la institución a fin de analizar la conveniencia de  la introducción de un guaraní comunicacional en la malla  curricular de la carrera de Enfermería y de Obstetricia,  que ayude en gran medida a la compresión y uso correcto del idioma guaraní y que  podría representar la solución  práctica a este problema detectado.

\   

# Revisión de la literatura
## Marco legal
Se transcriben a continuación los capítulos I-II y IV de la Ley de Lenguas por ser promulgada recientemente y poco conocida aún por los estamentos universitarios, además se considera hallarse aquí los pilares fundamentales que sustentan  esta investigación.

Con la promulgación de esta ley se pretende que el idioma guaraní logre la misma jerarquía que el castellano, evitando de ese modo la diglosia, es decir la preeminencia del castellano sobre el guaraní.

\   

### Ley No. 4.251: Ley de Lenguas
#### Capítulo  I
- **Art. 2º. De la pluriculturalidad.** El Estado paraguayo deberá salvaguardar su carácter pluricultural y bilingüe, velando por la promoción y el desarrollo de las dos lenguas oficiales y la preservación y promoción de las lenguas y culturas indígenas. El Estado deberá apoyar a los esfuerzos para asegurar el uso de dichas lenguas en todas sus funciones sociales y velará por el respeto a las otras lenguas utilizadas por las diversas comunidades culturales en el país. 
- **Art. 3º. De las lenguas oficiales.** Las lenguas oficiales de la República  tendrán vigencia y uso  en los tres Poderes del Estado y en todas las instituciones públicas. El idioma guaraní deberá ser objeto de especial atención por parte del Estado, como signo de la identidad cultural de la nación, instrumento de cohesión nacional y medio de comunicación de la mayoría  de la población paraguaya.
- **Art. 5º. De la promoción de las lenguas originarias.** El  Estado promoverá la preservación y el uso de las lenguas originarias de América, tanto en el país como en las organizaciones internacionales en las que participe. 

\   

#### Capítulo II: De los Derechos Lingüísticos
* Art. 9º.- De los derechos lingüísticos individuales: Todos los habitantes de la República tienen derecho a: 
1.- Conocer y usar las dos lenguas oficiales, tanto en forma oral como escrita, y a comunicarse con los funcionarios públicos en general en una de ellas. Los ciudadanos indígenas tienen además el derecho a conocer y usar su lengua propia.
2.- Recibir información en su lengua, de parte de los empleadores privados,  en los temas laborales y administrativos de interés general.
3.- Recibir información oficial en guaraní y en castellano a través de los medios de comunicación del Estado o de los medios de comunicación privados que emitieren información oficial del Estado. 
4.- No ser discriminado por razón de la lengua utilizada. 
5.- Utilizar cualquiera de las dos lenguas oficiales ante la administración de justicia y que sus declaraciones sean transcriptas en la lengua elegida sin mediar traducción alguna. La persona usuaria  de otra lengua tiene derecho a ser asistida en juicio por personas que conozcan  su idioma.
6.- Recibir desde los inicios del proceso escolar la educación formal en su lengua materna, siempre que la misma sea una de las lenguas oficiales del país o una lengua indígena).

CAPÍTULO - IV
De los Idiomas en la Educación
* Art. 26.-  De la alfabetización en lengua materna.  El niño y la niña que habiten el territorio nacional tienen derecho a recibir educación inicial en su lengua materna, siempre que la misma sea una de las lenguas oficiales del Estado).
Los pueblos indígenas utilizarán en la etapa inicial de la educación escolarizada sus respectivas lenguas. 
Las demás comunidades culturales optarán por una de las lenguas oficiales. 
* Art. 27.- De la participación de la comunidad educativa. El Ministerio de Educación y Cultura dará participación a la comunidad educativa en la toma de decisiones acerca de la elección de la lengua de alfabetización inicial. La elección del diseño de educación bilingüe resultará de la aplicación de instrumentos de evaluación de competencia lingüística al educando y de los compromisos colectivos asumidos por la comunidad educativa. 
* Art. 28.- De la enseñanza de las lenguas oficiales. Las lenguas oficiales serán enseñadas en las instituciones públicas y privadas que integran el sistema educativo nacional, aplicando métodos que garantizan la máxima eficacia comunicacional.  
* Art. 29.- De las lenguas oficiales como instrumentos didácticos. Las lenguas oficiales serán utilizadas como medio en la enseñanza en todos los niveles del sistema educativo: inicial, escolar básica, media y superior, de conformidad con la competencia requerida para cada nivel. Interpretar
* Art. 30.- De la formación del profesorado. Los centros de formación docente deberán preparar educadores bilingües, en guaraní y castellano.  Según las circunstancias, en su ejercicio docente, los profesores emplearán las dos lenguas oficiales como medio didáctico. Dentro  del territorio de una lengua indígena, deberán ser  formados también en esa lengua, la cual se empleará adicionalmente  como medio didáctico.

	De igual modo los estudiantes de Enfermería y de Obstetricia y  los profesionales de estas especialidades en el desempeño de su profesión, deben hacer uso del idioma guaraní, teniendo en cuenta que los usuarios que recurren a los hospitales públicos corresponden a ese 37% de la población paraguaya mono hablante guaraní y proveniente del interior del país.

Antecedentes del Bilingüismo
Lo que se puede llamar bilingüismo, comenzó en Paraguay a mediados de la era del gobierno del Pte. Stroessner, y más concretamente a partir del tratado de Itaipú en 1973. El Paraguay, aún conquistado y el mestizo, no fue bilingüe, aunque tuviera en su seno una isla de castellano- hablantes que se servían del castellano más para la comunicación externa que la interna.
      El grueso de la población criolla y mestiza, así como la totalidad de los pueblos nativos, administrados por los padres del clero secular, por franciscanos y jesuitas eran comunidades exclusivamente monolingües. La lengua en el Paraguay no seguía la curva de la "raza", sino las de la comunidad local, en la que se confundían criollos, españoles, mestizos, indios, negros y pardos.

Una Nación, dos Culturas
El Paraguay, que no siempre ha logrado ser un buen estado- excepto tal vez en tiempos del Dr. Francia - y que mucho menos ha gozado de buenos gobiernos, es desde por lo menos el siglo XVII, una buena nación. La nación se suele entender  como un grupo de personas en comunidad con una particular conexión con una tierra- lugar de nacimiento, patria, situación ecológica-, con una continuidad histórica- tradición, hábitos, hechos ocurridos con cosas  hechas- y con un destino común sentido como tal. La nación es un ñandeva, que se define frente a los otros como un oréva.
      La cultura es la realización de un modo de ser propio por miembros de una comunidad histórica. Este modo de ser que es fundamentalmente modo de hacer y modo de pensar, se explica en formas de expresión que son formas de entender y entenderse en el mundo e instrumentos para trabajar este mundo- lengua, arte, sistema social, religión, cultura material-. La cultura como modo de ser está por lo menos implícita en todo grupo humano constituido en Nación hasta tal punto que la nación se define en último término por su autonomía cultural y dura mientras dura su cultura y no más allá. Deculturizar es de hecho desnacionalizar.
      La cultura está trabajada continuamente por la historia y trabaja la historia. Es dentro de la historia y no fuera de ella que se establece la verdadera lucha de la nación por su cultura, por una cultura nacional. La lucha por la cultura es esencial a una nación, sobre todo si se tiene en cuenta que la cultura no es un capítulo aparte de la lucha por una economía nacional y por una política nacional.

Cultura de Alianza y Paz
Con la promulgación de la Ley de Lenguas, Paraguay aspira a cambiar una realidad: romper el desequilibrio entre los idiomas oficiales, el guaraní y el castellano, donde si bien el primero es mayoritario, lo habla un 86 por ciento de la población, no alcanza áreas formales del Estado ni espacios de poder.
      De esta manera, el gobierno busca hacer efectivo el mandato constitucional que en 1992 proclamó al Paraguay como un país pluricultural y bilingüe, un concepto que es meollo de las discusiones en torno a cómo revalorizar el guaraní y terminar con el bilingüismo diglósico, es decir, un sistema donde una de las lenguas tiene un tratamiento superior a la otra.
      Con el bilingüismo diglósico se justifica la causa de la dificultad por la que gran parte de los jóvenes no habla o habla poco o no interpreta los mensajes emitidos por su interlocutor, porque el guaraní a pesar de haberse proclamado la  obligatoriedad de su enseñanza, se halla  relegada a un segundo plano, restándosele  importancia en la educación y como una expresión genuina  de paraguayidad.
      El conocimiento y el uso del idioma guaraní, por parte de los profesionales del área de Enfermería y de Obstetricia es un obligación, sobre todo si pretendemos acompañar las políticas públicas en Salud que pregona la inclusión y la no discriminación, por estas razones y otras más, la necesidad  conocer y de  comunicarse en el idioma guaraní es imperiosa.
      Aquel artículo constitucional, el 140, fue un acontecimiento histórico que quedó en lo simbólico porque a excepción de la educación, ese reconocimiento no se hizo en ningún otro ámbito: una paradoja en un país de seis millones de habitantes, que con las comunidades de Argentina, Bolivia y Brasil suma un total de 10 millones de hablantes del idioma guaraní.
      Recién en el año de su Bicentenario Paraguay empieza a trabajar con la cuestión bilingüe, mediante la reglamentación de una ley que impone, entre otras cosas, la creación de una Academia de la Lengua Guaraní para definir un alfabeto y una gramática oficial.
      Un proceso absolutamente necesario, en un país donde cuatro quintas partes de los pobladores hablan esa lengua y todavía tienen inconvenientes para sacar cédulas de identidad o hacerse entender en hospitales y tribunales judiciales.
      En cuanto a la enseñanza, el artículo 77 dice que "se instruirá asimismo en el conocimiento y en el empleo de ambos idiomas oficiales de la República".
      El Guaraní es una lengua descriptiva, y expresada en ella los conocimientos de la anatomía humana (avarete), la fisiología (tetereko), la patología (mba'asykuéra) y la higiene (ñemopotî), la cura y el tratamiento son seguros, porque de esta forma, al comunicarse en esta lengua que maneja la mayoría de la población, cuenta con la colaboración del paciente. 	
      La enseñanza del guaraní en la Reforma Educativa, no debe apreciarse como "un simple proyecto educativo para aprender un idioma"; sino que, debe ser considerado como el instrumento político que cooperará indudablemente en el fortalecimiento socioeconómico y cultural del país. El guaraní es una lengua descriptiva.
      La historia de la República del Paraguay registra el protagonismo de la lengua guaraní como factor de identidad de los paraguayos, esencialmente. Así, desde la misma independencia nacional se tienen testimonios que señalan su utilización como medio de comunicación de los próceres de aquella gesta libertaria; a tal punto que el santo y seña que ayudo a abrir el Cuartel de la Rivera fue expresado en lengua guaraní. por otra parte cabe destacar la importancia gravitante y manifiesta de la lengua guaraní -único medio de comunicación de los combatientes paraguayos- en las dos guerras que sostuvo el Paraguay contra la triple alianza primero (1865-1870); y luego contra Bolivia (1932-1935) en la denominada guerra del Chaco).
      Tras la Guerra del Chaco, aparece una generación de estudiosos que demostraron sumo interés por la recuperación y promoción de la lengua guaraní, entre quienes se destacan varios intelectuales Prof. Dr. Reinaldo Julian Decoud Larrosa, el Dr. Moisés Santiago Bertoni, el Padre Antonio Guash, y otros; que en forma individual o colectiva a través de asociaciones, estudiaron la lengua y la cultura guarani. Aquí, haciendo digresión momentánea, conviene señalar que muchos hombres de ciencias se acercaron a estudiar e investigar todo lo concerniente al guaraní, en todo tiempo, así se puede citar a KurtUnkel, EgonSchagen, o los religiosos que llegaron con los conquistadores como el Padre Anchieta, Restivo o Ruiz de Montoya. 
      El Idioma Guaraní es el idioma de la mayoría. Los resultados del  Censo Nacional, del 2002, practicado en el Paraguay, evidenciaron que el 37% de la población de casi cuatro millones y medio de habitantes, es monolingüe guaraní, el 50% bilingüe (guaraní-castellano), el 7% monolingüe castellano, y el 6% restante hablante de otras lenguas. El guaraní es el idioma mayoritario de los jóvenes, según la Encuesta Integrada de Hogares 1997-1998, respecto del idioma que hablan la mayor parte del tiempo en el hogar los jóvenes entre 15 y 29 años de edad. La encuesta revela un 50,4% de guaraní-hablantes, un 27,8% de bilingües (guaraní-castellano), un 19,3% de hispanohablantes, y un 2,5% restante hablante de otras lenguas.
      Teniendo en cuenta el alto porcentaje de guaraní hablante y guaraní bilingüe presentado por la Dirección General de Encuesta Estadística y Censo ( DGEEC), se considera que la inclusión en la malla curricular de un guaraní técnico, en las carreras de Enfermería y de Obstetricia, fortalecerá y contribuirá efectivamente  a que el estudiante futuro profesional de salud sea aun más competente al tener dominio de  ambas lenguas. La facultad de Derecho en la  carrera de Ciencias Sociales y Políticas, fundamenta respecto al idioma guaraní cuanto sigue: resulta aún más necesaria fortalecer la comprensión de la Lengua Guaraní, además de tener presente que La Constitución Nacional del Paraguay de 1992 en el Art. 140 establece y enuncia claramente que: "El Paraguay es un país pluricultural y bilingüe. Son idiomas oficiales el Castellano y el Guaraní. La ley establecerá las modalidades de utilización de uno y otro. Las lenguas indígenas, así como las de las otras minorías forman parte del patrimonio cultural de la Nación.

Evolución Histórica del Idioma Guaraní
A principios del siglo XX aparecen tímidamente algunas publicaciones que transmitían  el pensamiento guaraní, principalmente en forma de poesía y canciones populares, y luego aparece  el teatro de Julio Correa, gran intérprete del pensamiento campestre. Una camada  de autores populares salió a luz, muchos de ellos utilizando un guaraní muy puro, apenas con ciertos hispanismos necesarios, mientras que otros han utilizado la expresividad del guaraní con frases enteras en español, habla conocida como "yopará" (de jopara, que significa mezcla).
      El yopará empezaba así a instalarse muy fuerte en lo escrito, desafortunadamente con admisión popular, para desesperación de los lingüistas guaraniólogos y los que adoraban la lengua autóctona castiza. Este feo modo de hablar, propalado por los citadinos que presumían de hablar el guaraní, ha sido transmitido desde entonces por los medios de comunicación, degenerando la belleza nativa.
      Al respecto en el libro "Ñandeípícuéra dice: se puede afirmar con el científico Dr. Moisés Bertoni que los poemas de don Narciso R. Colmán, escribiendo en guaraní salvaguardó a su lengua vernácula en un tiempo en que este  idioma tropezaba en la sociedad paraguaya con serias hostilidades. Dio un ejemplo de la lucha por la cultura autóctona sacando del olvido leyendas  guaraníes y aportando apasionadamente a un mejor conocimiento y uso del idioma guaraní.
      Desde 1932, el Paraguay sufre de nuevo otra guerra, esta vez contra Bolivia, antes de recuperarse de la anterior. Conocida como la "Guerra del Chaco", ésta fue propiciada por una compañía petrolera estadounidense ubicada en Bolivia, que quería evitar que otra Alemana explorara el territorio paraguayo en busca de petróleo. Apoyados por aquella, los bolivianos invadieron el chaco paraguayo. Los paraguayos, al ver que estaban siendo sacrificados por los intereses totalmente ajenos, nuevamente se refugiaron en la lengua guaraní, y otro auge poético vio la  luz, donde el tema principal era el patriotismo y la defensa de la patria: para las canciones, son las del grupo Chakorepurahéi (canciones del Chaco). 
      Cuentan que cierta ocasión el ejército boliviano acudió a un indígena, también boliviano, para la interpretación de mensajes interceptados por radio. Éste, al reconocer la lengua como la suya, sufrió un ataque nervioso (real o simulado), de tal magnitud que no pudo traducir nada. Tal era la unión  y fidelidad que producía el idioma guaraní entre sus habitantes.
      La guerra de nuevo se sirvió del guaraní para confundir al enemigo, y al terminar, con 50.000 paraguayos y 80.000 soldados bolivianos de menos, Paraguay no recuperó todo su territorio original, pero se quedó con la antología poética llena de relatos y esperanzas. Y, una vez más, el gobierno paraguayo siguió  ignorándolo en las escuelas y universidades, por varias décadas más.
      A mediados del siglo pasado, un cura español, Antonio Guash, gran seguidor de Anchieta y Montoya, publica sus propias investigaciones acerca del guaraní. Su obra consta de una completísima gramática, El idioma guaraní, al que luego agregó una antología de prosa y verso; y Diccionario castellano-guaraní y guaraní- castellano. Guash aportó varias ideas a la nomenclatura gramatical, que luego fueron oficialmente adoptadas.
      También por esa época, Anselmo Jover Peralta reúne el vocabulario guaraní y las anotaciones de gramática guaraní dejados a su muerte por Tomás Osuna, los que enriquece, le agrega algunos apéndices, y publica el Diccionario guaraní-español y español -guaraní. En el prefacio de esta obra, Peralta se quejaba de la triste suerte del idioma guaraní de esa época.
      Por fin, la constitución Nacional Paraguaya de 1967 reconoce la existencia del guaraní, pero el idioma oficial sigue siendo el español. Aún así, empieza lentamente una difusión oficial del idioma. Años después algunos institutos empiezan a enseñarla con el apoyo del Ministerio de Educación, a lo que seguiría en la enseñanza media como materias complementarias, y los políticos de turno utilizaban por doquier- tal como hoy- el yopará en sus campañas proselitistas.
      En 1989 Paraguay sale de una larga dictadura, y la siguiente Constitución Nacional (1992) ya reconoce al guaraní como idioma oficial del país, en un mismo nivel que el español. Inmediatamente se implementa su uso obligatorio en la educación escolar básica,  y luego en  el nivel medio, con una educación bilingüe. El guaraní ha sido debidamente reconocido.
      Se ha criticado mucho la manera en que las autoridades educativas paraguayas están manejando actualmente la enseñanza de esta lengua. Esto, principalmente en lo que se refiere al enriquecimiento del vocabulario: hay quienes detestan la generación del neologismos "en laboratorios", y otros que no ven con buenos ojos la creciente ola de hispanismo provenientes del guaraní popular, el yopará, que utilizan letras inexistentes en el alfabeto guaraní, y principalmente, atentan contra la estructura silábica del guaraní oficial.

Características del Idioma Guaraní
El Guaraní es una lengua descriptiva, y expresada en ella los conocimientos de la anatomía humana (avarete), la fisiología (tetereko), la patología (mba'asykuéra) y la higiene (ñemopotî), la cura y el tratamiento son seguros, porque de esta forma, el médico, al comunicarse en esta lengua que maneja la mayoría de la población, cuenta con la colaboración del paciente.
      Para llenar la ficha médica, hablada y redactada en castellano, hace incomprensible para el 87% de la población paraguaya, porque su lengua materna es el guaraní. "Si el estudiante o médico pregunta en castellano, la mayoría de los pacientes no responde. Sin embargo, al preguntar en guaraní, no solo responden, sino que agregan observaciones de mucha importancia para el llenado de la ficha médica. Preguntarle en Castellano al Guaraní parlante si siente algún malestar en las vías urinarias, lo más probable es que no responda".
	Al preguntarle en Guaraní, mba'épa reñandu ndetyrapépe, lo más probable es que le contestará con detalles y precisión lo que le acontece. Otro ejemplo si el estudiante pregunta al paciente; Usted tiene oligofagia, quedará mudo el paciente. Si le pregunta, ndépa rekaru'i térâ rekarupokâ, la respuesta no se hará esperar. El Guaraní está muy asociado con la naturaleza del cuerpo y dicha en ella es muy expresiva y precisa.
	Al estudiante se le debe enseñar la importancia del conocimiento del guaraní y que la misma no disminuirá su saber, sino todo lo contrario, el saber sacude la ignorancia, además, generalidades médicas y en la lengua guaraní cómo deben ser expresadas. Por ejemplo uno dice en Guaraní hasychéve che akâ y es incorrecta, debe ser akârasy, y muchos ejemplos más. Expresiones folklóricas como tirisia (hispano) equivalente en Castellano, ictericia. Además saber preguntar y elaborar un cuestionario médico en guaraní, cómo llevar a cabo una consulta médica; historia médica con antecedentes personales, patológicos y enfermedades actuales. El uso del Guaraní, independientemente de que guste o no, es competencia básica para ejercer la profesión médica y así asegurar a una mejor comprensión entre el profesional y el paciente. 
	El guaraní no es tema de la Medicina, sino que es necesario conocer cómo el pueblo designa las enfermedades o males que lo aqueja. Además, existen vocablos folklóricos como el kambyryrujere, haru, py'aruru que cualquier Médico y estudiante debe saber, por una necesidad psicológica y no confrontar culturas, sino sumergirse en ellas y desde esa óptica revertir conocimientos científicos.

Inclusión y Exclusión a través de Idioma GuaraníFinal del formulario
En Corrientes, provincia de la República Argentina,  hubo un tiempo, que en parte se prolonga hasta hoy, en que se decía: aquí todavía se habla guaraní. Este todavía para algunos era afirmación de tradición persistente. Para otros una marca poco honrosa de tiempos pasados destinados al olvido. Lo cierto es que hoy es raro escuchar esa lengua en la población urbana de Corrientes; ha dejado de ser un hecho social. 
      Hasta entrado el siglo XXI el guaraní ha sido la lengua mayoritaria y  casi exclusiva del Paraguay. Pero nunca ha sido reconocida como lengua propia. Hay que decir que ni los mismos guaraní parlantes se atreven a reclamar al guaraní como lengua propia, como lo han ido haciendo países como la República Checa que se decidió por el checo en vez del alemán, Sri Lanka (Ceylán) cuando reemplazó el inglés, signo de colonia, por el sinhala como única lengua oficial, o Catalunya y Galicia que en una España plurilingüe declaran el catalán y el gallego como lenguas propias de sus gobiernos autónomos, pero no separatistas. De ninguno de ellos puede decirse que haya retrocedido en términos de desarrollo humano debido a su elección. El plurilingüismo en los Estados es un hecho de alcance mundial.
      Por otra parte la ciudadanía necesita una o unas lenguas para promover la comunicación tanto interna como externa, a veces se impone una elección, que tiene mucho de opción. ¿Cómo podría mantenerse la libertad cultural o simplemente la libertad, si una o más lenguas habladas, la lengua guaraní en el caso del Paraguay, amplia y mayoritariamente hablada por la población, es coartada en sus derechos a la comunicación? 
      La historia colonial del Paraguay no fue de persecución al guaraní. Sin embargo, hubo en el uso del guaraní dos ramificaciones muy significativas. En el Paraguay colonial criollo, la lengua guaraní absolutamente mayoritaria, especialmente entre las mujeres, convivía con el castellano, que era la lengua de la escritura, de la documentación, de la ley, de la escuela. Se ha instaurado ese cuadro que más recientemente se denomina "diglosia", en la sociolingüística. En el Paraguay colonial indígena, la lengua guaraní fue la lengua no solo mayoritaria sino del gobierno interno, de la escritura, de la escuela, de la trasmisión de las leyes. Lo curioso del caso es que casi toda la literatura colonial en guaraní fue producida en ese ambiente, y está registrada en libros, no sólo de gramática y diccionarios, sino en una amplia literatura religiosa en guaraní, y sobre todo en una literatura histórica guaraní, creada por los indígenas hablantes de esa lengua que hizo valer incluso su papel y derecho de interlocutor con las autoridades de la Corona española.
	El Paraguay moderno ha heredado la diglosia, aún en esta época contemporánea en que tenemos el guaraní reconocido como lengua oficial, si bien con poca oficialidad. Los signos de  exclusión del guaraní son llamativos y generales que ya ni siquiera resultan extraños. En 1992 la Constitución llegó a una declaración sin duda honrosa y justa para la lengua guaraní al reconocerla como lengua oficial, la política lingüística a ese respecto está lejos de ser explícita y estar debidamente articulada. Aquí no se trata de una lengua en sí, sino de sus hablantes y de la libertad cultural a la que tienen derecho en el uso de la propia lengua. Si bien es cierto que nadie es dueño de una lengua, ni siquiera el estado, la política del estado tiene el deber de asegurar que las lenguas de sus miembros sean   protegidas  y promovidas, defendiendo si fuere el caso. Con cada pérdida cultural el Estado se hace más pobre y menos creíble. Un Paraguay sin Guaraní es un Paraguay sin montes y sin agua. Las fuentes de la libertad cultural, una vez taponadas, no siempre surgen en otro lado por vía de compensación.

La Paraguayidad
Uno de los méritos que tiene el Paraguay es su identidad cultural, aun con toda su pobreza. El país fue expuesto a múltiples saqueos. Hay repetidas intervenciones desde afuera y de múltiples formas. La iglesia de la contrarreforma en el siglo XVII, las leyes de indias promueven un modelo que no tiene en cuenta la diversidad cultural de los pueblos conquistados, aunque se aceptan notables aspectos culturales, como la lengua. En esto consiste la colonización.
      Después de la Guerra de 70 se desarrolla, a lo largo del siglo XX, una segunda colonización, mediante la apropiación de las tierras del Estado y el comercio de productos importados, que se acentúa sobre todo a partir del tratado de Itaipu, en 1973,  y que se prolonga hasta ahora mediante la ideología de la globalización.

Mito y Representación
El análisis histórico, social y cultural nos hace ver, sobre todo ahora, que los paraguayos no somos todos iguales. A partir de la guerra del 70 sufrió una nueva recolonización que casi nunca se ha analizado. Esta nueva colonización tiene ingredientes que ya no son españoles, son alemanes, coreanos, italianos, franceses, coreanos, japoneses y chinos, pues aunque pocos en número, mantienen forma de vida que se distancian considerablemente del Paraguay, aunque ellos ya son paraguayos. Estos datos que recoge el Censo 2002, dan pie a que se pueda considerar el mito de la unidad como mito ideológico. Se impuso la lectura de los grupos hegemónicos; se despreció el guaraní, el ñandereko, se los alineó a lo malo, a lo de baja calidad o escasamente productivo.
      Lo que debería entenderse es que cuando tratamos de hurgar en nuestros orígenes y en nuestra esencia, es porque además de pretender una representación auténtica de nuestra colectividad, tenemos la obligación de aportar algo distinto a la colectividad mundial. Pero no podemos hacerlo por la manifiesta discapacidad que llevamos a cuestas: no hablamos guaraní, no conocemos a nuestros poetas, no conocemos nuestra música. Ni tenemos bagaje cultural alguno que nos represente, ni para representar-con calidad- nuestra propia entidad nacional. El factor económico, nos afectó decididamente. Pero hay que señalar que muchas cuestiones económicas se fundan en lo cultural.
La Lengua Guaraní en el Mercosur
El guaraní es una de las 28 lenguas de la familia Tupí guaraní, sin duda la de mayor extensión geográfica y de uso generalizado por poblaciones que hoy no se identifican como indígenas u originarias; a las que más fácilmente se las caracterizaría con el ambiguo mote de mestizas. 
      La distribución lingüística de los hablantes en el Paraguay, a partir de datos provenientes del Censo de Población y Vivienda de 2002, de la Dirección General de Estadística, Encuestas y Censos lo presenta  de este modo:
* Pueblos indígenas: 87.099 - 1,8%
* Guaraní parlantes: 1.399.220 - 27,0%
* Guaraní bilingües: 1.721.200 - 33,0%
* Castellano bilingües: 1.330.810 - 26,0%
* Castellano parlantes: 411.780 - 8,0%
* Idioma portugués: 122.520 - 2,4%
* Idioma alemán: 36.200 - 0,7%
* Idioma japonés: 3.210 - 0,1%
* Idioma coreano: 2.810 - 0,1% 
* Otros idiomas no indígenas: 3.960 - 0,1%
De estas cifras resulta, el siguiente cuadro:
* Guaraní: 3.120.420 - 60,0%
* Bilingüe (guarani-castellano): 3.052.010 - 59,0%
* Bilingüe (castellano-guaraní): 1.330.810 - 26,0%
* Castellano: 411.780 - 8,0% (16).

La Multiculturalidad
Frente a este fenómeno que se juzga enriquecedor para el bien de la humanidad y que ha dado admirables frutos de sabiduría y modos de ser en el mundo, han interrumpido también en la historia proyectos de unificación y uniformidad que pretenden reducir el número de lenguas y de culturas.
 	La cuestión de la multiculturalidad y plurilinguismo surge en el momento en que  se toma conciencia de la uniculturalidad y el unilinguismo son las mayores amenazas para las sociedades de los hombres libres.
      La multiculturalidad según diferentes definiciones, se refiere a la coexistencia de grupos de personas que se identifican con culturas diversas en un espacio social dado.

El Idioma Guaraní en la Realidad Multicultural
La relación del guaraní con otras lenguas indígenas de Paraguay no es del mismo orden que la del guaraní con el alemán, el inglés, el portugués y el castellano. Y aquí surge la pregunta de si el llamado guaraní paraguayo ha de ser tenido todavía como lengua indígena y hasta qué punto su relación con el castellano es enteramente intersistemática.  El guaraní del que se considera a sí mismo como hablante de guaraní, aun el hibridizado  sigue siendo lengua indígena, aunque no de una sociedad indígena. La conversación entre un hablante de guaraní paraguayo y un paraguayo hablando castellano paraguayo, no se sitúan necesariamente en dos sistemas y su relación podría ser intrasistemática. Los sistemas culturales están sujetos a modos de interpretación muy variados, que privilegian ya sea lo económico, lo religioso, lo político o los determinismos históricos, por citar algunos.
      Cuestiones tan simples como una gramaticalización no única ni uniforme sino aceptable, quedan por definirse; y el tema es que hace trescientos años  ya se había conseguido. La normalización de acepciones y neologismos del léxico moderno, que ya existen, pero que no logran salir del ámbito restricto de la domesticidad en la que fueron creados, es otra asignatura pendiente. Y en resumen, la práctica del discurso político y económico está lejos de ser habitual. Poco a poco, sin embargo, se están produciendo textos legislativos en guaraní, aunque sean traducción del castellano. Si esta práctica y esos usos continúan, dentro de 10 ó 15 años  se podrán percibir resultados sensibles.

El Guaraní: La Lengua más Viable de América
Por las condiciones apuntadas y en conocimiento de que ninguna otra lengua americana se halla en las condiciones sociales, políticas, jurídicas y culturales en que se halla el guaraní en el Paraguay, esta lengua es de entre todas, la más viable de América.
      Es una lengua asumida por una comunidad nacional no indígena; su uso se extiende a todo el país y tiene como reservas a cerca de un millón de monolingües de este idioma entre la población mestiza y a las seis parcialidades indígenas en sus respectivos hábitat; tiene el rango jurídico constitucional de ser lengua oficial del Estado; pero sobre todo, es la lengua que le da su identidad cultural propia al Paraguay y al paraguayo, porque es lengua materna de más del 85% de los paraguayos. El guaraní es una lengua estudiada y descripta desde hace más de cuatro siglos; Por todo ello el guaraní se halla ubicado en la vanguardia de la lucha por la identidad de América, donde sus 28 Estados soberanos funcionan en lenguas europeas.
      El funcionamiento normal del guaraní en el Paraguay significaría la salvación de la primera lengua americana y la esperanza de salvación de muchas otras. Pero si el guaraní sucumbiera en su intento, todas las demás lenguas americanas quedarán signadas por la amenaza de la desaparición. En suma, la causa del guaraní es una causa de América, y además, es la causa de la corriente que promueve el multilingüísmo y de la multiculturalidad en todos los rincones del planeta.

La Situación Sociolingüística del Guaraní en el Paraguay
La situación social de la lengua guaraní en el Paraguay es descripta por los sociolingüistas como diacrónico, diatópica y diastrática. Tiene la antigüedad del Paraguay mismo; no reconoce barreras geográficas ni estratos sociales; no está regionalizada ni confinada a enclaves étnicos. Aquí el idioma guaraní es hablado por toda la población nacional e involucra a todos los estratos sociales desde los orígenes del Paraguay.
      Esta descripción sociolingüística la presenta como una lengua de vigorosa presencia en el país, pero esta parcializada; dicha primera presentación pierde fuerza cuando se le agrega la cuarta característica; es decir, su carácter de lengua en contacto y en situación diglósica con el castellano. Es verdad que el guaraní comparte con el castellano el mismo territorio y la misma población en el Paraguay, pero no comparte el mismo nivel social ni la misma área de cobertura en cuanto a los tópicos o temas abordados en el uso.
      El castellano es usado por los paraguayos en forma exclusiva en el ámbito del estado, del gobierno, de la prensa, del sistema educativo y la convivencia social de la alta sociedad. Por su parte el guaraní es relegado al uso en las relaciones personales de intimidad, al seno familiar, a las relaciones de confianza, al ámbito rural, al ámbito del proletariado citadino, a las cuestiones no oficiales y a las conversaciones informales. 
      Por lo general el paraguayo es bilingüe pero su bilingüismo no es coordinado sino incipiente o subordinado y sobre todo diglósico. Hace uso de uno u otro idioma según las circunstancias. Para las cuestiones formales u oficiales usará indefectiblemente el castellano; también se dirigirá en castellano al desconocido así como al extranjero.
      Lo usa también como idioma secreto entre paraguayos en el extranjero o dentro del Paraguay frente a extranjeros o citadinos monolingües castellanos. Tampoco satisface a los paraguayos los chistes y las canciones que no sean en guaraní, ni el uso de otro idioma cuando celebran un encuentro fuera del país.
A toda esta situación diglósica debemos agregar la situación predominante de uso oral del guaraní frente al uso más escrito que oral del castellano. 
      Hasta una década atrás el guaraní se hallaba fuera del sistema educativo y remontándonos al pasado encontramos que se hallaba terminantemente prohibido en el ámbito escolar. En las últimas décadas ingresó al sistema educativo pero con un enfoque lingüístico absolutamente equivocado que generó su rechazo por los propios hablantes del idioma, situación aprovechada por los castellanistas para promover el regreso del sistema educativo al monolingüismo castellano.
      En suma, el guaraní es una lengua minorizada siendo lengua de mayoría y el castellano lengua mayorizada, siendo lengua de minoría. El castellano cubre todo el universo de las necesidades humanas de comunicación, mientras el guaraní se halla reducido a temas determinados.

La Situación Psicolingüística del Guaraní en el Paraguay
Para quien no conoce la función alienante del colonialismo cultural no es fácil comprender la actitud del paraguayo hacia la lengua guaraní. Este fenómeno enajena mentalmente a la persona hasta el punto de apartarlo de sus propios intereses; desfigura su personalidad y lo lleva hacia la negación de su yo esencial.
      El colonizado renuncia a su cultura propia y pasa a asumir los valores culturales del colonizador. La cultura colonialista tiene la virtud de prolongarse por siglos en una sociedad. En el Paraguay este fenómeno permanece intacto; nunca se ha retirado a pesar de 200 años de vida independiente. Su presencia configura situaciones de crueldad porque sostiene un colonialismo interno, una sujeción de paraguayos a paraguayos por causa de lenguas diferentes. Asunción, la ciudad capital del país, es la única de Sudamérica que no ha elaborado una cultura propia, citadina, metropolitana, diferente y opuesta a la cultura interiorana. Asunción es una ciudad con cultura rural; sus habitantes consumen música, canciones, teatro y otras manifestaciones artísticas elaboradas por gente del interior y por lo general en guaraní.

El Idioma Guaraní en el Ámbito Ocupacional
El  Ministerio de Salud Pública y Bienestar Social, a través de la Dirección Gral. de Recursos Humanos,  en las convocatorias  a  concurso público de oposición de  méritos y aptitudes, para la contratación de  personal de blanco,  indica dentro del  perfil requerido, la capacidad de comunicarse en el idioma  español y guaraní. 

	Idioma Guaraní: Se otorgará 5 puntos al que lo hable fluidamente. Por lo tanto, para la evaluación de este ítem se estará realizando una entrevista, por la Comisión de Selección. En la matriz  de entrevista figura: no comprende ni habla, comprende pero no habla y habla perfectamente.

El Idioma Guaraní en el Contexto Americano
Un Vehículo de Comunicación
El Curso de Diplomado en Lengua y Cultura Guaraní, promovido por la Universidad Nacional  de Itapúa, surge como una actividad de extensión de modo a expandir el conocimiento de la lengua guaraní en otras regiones, habida cuenta de la necesidad de conocerla y apreciarla en otros ámbitos atendiendo aspectos o planos que hacen a la lengua desde el punto de vista fonológico, morfológico, léxico semántico, sintáctico y pragmático.
      La lengua es por excelencia un vehículo de comunicación por lo que no existen fronteras para su análisis y tratamiento, y en ese contexto el Curso de Diplomado en Lengua y Cultura Guaraní propone la modalidad presencial y a distancia. Con ello se pretende dar respuesta a la necesidad de construir un puente para vincular la lingüística con las personas que lo requieren. La propuesta principal del curso está orientada a unir la teoría lingüística con la práctica.
      Con este proyecto, la Facultad de Formosa (Argentina), colabora para que la Universidad Nacional de Itapúa cumpla con las funciones fundamentales que hoy día la sociedad demanda a una Institución de Educación Superior: Docencia y difusión de la cultura, formación profesional, producción de conocimiento, investigación, y la extensión como un servicio a la comunidad.
      La incorporación de lenguas y culturas originarias (quechua, guaraní y qom), constituye una experiencia inédita de enseñanza a cargo de equipos formados por lingüistas y hablantes nativos. 
      La enseñanza de estos idiomas partió de un deseo de ampliar la oferta académica en un compromiso con la sociedad. Para estudiantes de antropología, asistentes sociales y trabajadores de efectores de salud, por ejemplo, el conocimiento de estas lenguas es un apoyo importante para su dinámica laboral.
      Teniendo en cuenta que en Rosario (Argentina), las comunidades correntina, paraguaya y qom son numerosas, con estos cursos, se intenta contribuir a la integración de estas personas, de acercarnos a ellas a través de su idioma y formas de vida. 
      Como parte de las metas sexenales, y de forma inusitada, la Secretaría de Educación Pública -SEP- (México) ha anunciado que antes de que termine este periodo procurará lograr la incorporación de la enseñanza en lenguas indígenas desde la primaria hasta el nivel de licenciatura. Los docentes serán previamente capacitados para impartirla. La Coordinadora General de Educación Intercultural y Bilingüe explicó que por primera vez se tratará de que los maestros estudien su lengua y aprendan a hablarla bien, pero sobre todo a escribirla, porque hasta ahora no ha habido dónde aprendieran a hacerlo, pues no todas las 62 lenguas originarias que le quedan al país cuentan con un alfabeto. Muchas están en peligro de extinción precisamente por carecer de él, y sólo son habladas por adultos y ancianos que no saben leer ni escribir.

Campaña Nacional por la Interculturalidad: "Habla en tu Idioma, es tu Derecho"
Según información oficial "en el Perú además del español, el quechua y aymara, coexisten una multitud de lenguas nativas. Aunque el español es el idioma de uso común, el quechua es una importante herencia del pasado inca y en muchas regiones del país aún se habla con ligeras variantes según la zona. 
      Existen además, otros dialectos como el aymara y diversas lenguas amazónicas que se reparten en una sorprendente variedad de familias con cerca de 15 troncos lingüísticos, dando lugar a 38 lenguas diferentes". Según documento de las Naciones Unidas educar a los niños de las minorías indígenas o de tribus exclusivamente en el idioma de la cultura dominante, en lugar de hacerlo en su lengua materna, perpetúa la pobreza. Existe la necesidad de reconocer nuestra condición de país multicultural y actuar en consonancia con ello. La brecha de la pobreza y la brecha del idioma son caras de la misma moneda. Sin embargo todas las actividades de la vida oficial, se realizan en español: la atención en las oficinas del Estado, la atención de la salud, el Poder Judicial, la comunicación oficial, etc. y todo el sector privado.  

METODOLOGÍA
Tipo de Estudio
Estudio observacional descriptivo de corte trasversal  prospectivo  con componente analítico.

Área de Estudio
El trabajo se desarrolló en el Instituto Dr. Andrés Barbero, situado entre las calles Cruzada de la Amistad y 6 de enero de la Ciudad de San Lorenzo. 
	La escuela de Enfermería se fundó en el año 1943, bajo los auspicios del Ministerio de Salud Pública y Bienestar Social. Desde su origen, forma parte del Instituto Dr. Andrés Barbero, iniciándose con un programa de dos años y otorgando el título de Enfermera Hospitalaria. De este programa egresaron 67 enfermeras. En el año 1952, la Escuela recibió una nueva orientación y se estableció un programa de enfermería, con una duración de 3 años otorgándose el título de Enfermera Graduada. Del programa egresaron 109 enfermeras.
	En el año 1963 logra su incorporación a la Universidad Nacional de Asunción con sus tres Escuelas, Servicio Social, Enfermería y la de Obstetricia. El programa abarca 4 años de estudio  y prepara al estudiante para optar por el título de Licenciado en Enfermería, hasta la actualidad.

Sujeto de Estudio
* Universo: Constituido por   estudiantes de la carrera de  Enfermería y de Obstetricia del Instituto Dr. Andrés Barbero de la UNA, Casa Central, matriculados en el año  2011.
* Muestra: Estuvo conformado por  los  estudiantes de las Carreras de Enfermería y de Obstetricia que accedieron a formar parte de esta investigación.
* Población enfocada: estudiantes de las carreras de Enfermería y de Obstetricia.
* Población accesible: estudiantes de las carreras de Enfermería y de Obstetricia del Instituto Dr. Andrés Barbero, Casa Central, año lectivo 2011.

Criterios
* De Inclusión
* Que sea estudiante  de la carrera de Enfermería y de Obstetricia del Instituto Dr. Andrés Barbero, casa central.
* De cualquier edad.
* De cualquier sexo
* De cualquier procedencia
* Que se encuentre en el lugar y tiempo del estudio
* Que acepte formar parte de la muestra.
* De Exclusión
* Estudiantes de otras filiales del Andrés Barbero
* Que no se halle en el lugar y tiempo del estudio
* Que no acepte formar parte de la muestra.

Unidad de análisis: cada uno de los estudiantes de las carreras de Enfermería y de Obstetricia.
* Tamaño de la muestra: Representada por el 54 % de la población. La muestra estuvo conformada  por los estudiantes de la Carrera de  Enfermería y de Obstetricia de la casa Central IAB que cumplieron con los criterios de inclusión.
* Muestreo: No probabilístico por conveniencia. 

Métodos, Técnicas e Instrumento
Para la realización de esta investigación se  utilizó un cuestionario estructurado con preguntas abiertas y cerradas, basadas en las variables de interés para este estudio, el mismo fue elaborado por la investigadora y  se aplicó a los estudiantes a través de la encuesta.
      Para medir el  grado de conocimiento y el uso del idioma guaraní  de los  estudiantes de las Carreras de Enfermería y de Obstetricia  se utilizó  una escala del 60% a saber:
      
60 o menos
Deficiente
De 61-70
Aceptable
De 71 a 81
Bueno
De 82 a 91
Muy bueno
De 92 a 100
Excelente
	A continuación se presentan los conceptos de conocimiento y grado de conocimiento desde la concepción de distintos autores, con la finalidad de lograr una mayor comprensión relacionada al tema en  estudio. 
	El conocimiento es un conjunto de información almacenada mediante la experiencia o el aprendizaje (a posteriori), o a través de la introspección (a priori). En el sentido más amplio del término, se trata de la posesión de múltiples datos interrelacionados. El conocimiento tiene su origen en la percepción sensorial, después llega al entendimiento y concluye finalmente con la razón, y es una relación entre un  sujeto y  un objeto. El proceso de conocimiento involucra cuatro elementos: sujeto, objeto, operación y representación interna (el proceso cognitivo). 
	Los grados de conocimientos según Platón, incluye la opinión (doxa) y la ciencia (epistéme). La opinión es un conocimiento basado en  las cosas sensibles y se mide  a través de la percepción. La ciencia es el conocimiento racional basado en los signos sensibles, el instrumento del conocimiento es la razón pero apoyada en signos sensibles o hipótesis.
	La epistemología define el conocimiento como un  conjunto de saberes, que se dan a diferentes niveles. El conocimiento se divide en tres niveles: el conocimiento sensible, el conceptual y el holístico. El conocimiento sensible es aquel que se adquiere a través de la captación de un objeto por medio de los sentidos, que en el caso de los seres humanos los más desarrollados son la vista y el oído. El conocimiento conceptual forma parte de un conjunto de representaciones definidas como invisibles,  inmateriales, universales y esenciales.  Por último, el conocimiento holístico denominado también intuitivo, hace referencia a la forma de captar los conceptos dentro de un contexto en particular, como uno de los elementos que componen una totalidad sin poseer una limitación o estructura bien clara.

Medición
Operacionalización de las variables
Variable 
Definición conceptual
Definición operacional
Categoría o escala de medición
Indicadores
Datos demográficos
 Conjunto de datos relacionados entre sí en cuanto a particularidades sociales,  culturales y geográficas de interés para este estudio.
Edad
Cuantitativa continua
Años cumplidos


Sexo
Cualitativa dicotómica
Masculino
Femenino


Estado civil
Cualitativa politómica
Soltero
Casado
Unión estable
Otros


Carrera
Cualitativa Nominal
Enfermería
Obstetricia

Variable

Definición conceptual
Definición operacional
Indicadores
Escala de medición o categoría
Uso del idioma guaraní


Cuanto habla y utiliza el idioma  guaraní en su cotidianeidad

Uso del idioma en su interrelación con el usuario guaraní hablante.

Nada

Poco

Mucho


Nominal ordinal

Conocimiento del idioma guaraní


Uso correcto del idioma en  su comunicación con el usuario guaraní hablante
Aplicación de su conocimiento  del idioma en la comunicación con el usuario guaraní hablante,  a través de las traducciones.



Deficiente
Aceptable
Bueno
Muy bueno
Excelente

Nominal ordinal



Grado de conocimiento del idioma guaraní



Acervo de conocimiento que posee sobre el idioma guaraní 
La batería de vocablo estará compuesta por 70 palabras de uso corriente en guaraní  en el trato entre el prestador y el usuario. Se calificará con base al  60% 
Deficiente
Aceptable
Bueno
Muy bueno
Excelente





Nominal ordinal



Interpretación en la comunicación con el usuario guaraní hablante
Descifra correctamente el mensaje emitido por el usuario guaraní hablante a través de las traducciones.
Interpreta el mensaje emitido por el usuario

Deficiente
Aceptable
Bueno
Muy bueno
Excelente

Nominal ordinal



Vocablos médicos utilizados en el idioma guaraní
Términos o vocablos que utiliza el guaraní hablante
Conocimiento de  vocablos médicos en guaraní
Deficiente
Aceptable
Bueno
Muy bueno
Excelente
Nominal ordinal


Identidad con el idioma guaraní






Sentimiento que manifiesta hacia el idioma guaraní, en cuanto a importancia, expresión, necesidad, emoción.
Aceptación
Indiferencia
Rechazo
Expresión del idioma.
Importancia del idioma guaraní en la historia.
Consideración del uso del idioma guaraní como una expresión de la paraguayidad.
Sentimientos que invade al hablar en guaraní
Cualitativa Nominal
Actitud para la inclusión del guaraní en la malla curricular
Si cree necesaria  la introducción del idioma en la malla curricular como un guaraní comunicacional
Aceptación
Rechazo
Si

No
Por que?...........

Nominal
Dicotómica






Control de Calidad 
* Se aplicó  los 5 primeros  cuestionarios a estudiantes de la casa de estudio  para verificar su validez,  estos   instrumentos   no formaron parte de la muestra.
* Se contó con  una semana de tiempo  para analizar  los inconvenientes  presentados  y realizar los ajustes necesarios para su aplicación.

Asuntos Estadísticos
Los datos obtenidos a través de la encuesta y que cumplieron  con todos los criterios de inclusión fueron tabulados y almacenados en una planilla Excel  para ser sometidos a un análisis estadístico descriptivo, y procesados con el programa  epi info.

Reclutamiento
Se solicitó   por escrito a las Directoras de las Carreras de Enfermería  y Obstetricia del Instituto Dr. Andrés Barbero", la autorización correspondiente, nota mediante, para acceder a los estudiantes de las respectivas carreras, explicándole previamente los objetivos y el alcance del presente  trabajo.
Con dicho consentimiento se accedió a los estudiantes para la aplicación de la  encuesta y la obtención de  los datos de interés para esta investigación,  por medio de un cuestionario, elaborado previamente para tal estudio por la investigadora.

Asuntos Éticos
Lograda la autorización de las autoridades de las Direcciones respectivas, se accedió a  los estudiantes a fin de explicarles los objetivos del estudio y obtener el consentimiento de los mismos para llevar adelante este trabajo de investigación. 
      El estudio se realizó respetando la confidencialidad y privacidad de los estudiantes que participaron de esta investigación. Este trabajo no supuso la presencia de peligro o daño alguno. Por el contrario   aportará datos de gran utilidad sobre el uso del idioma guaraní y dominio que presentan los estudiantes y a partir del mismo establecer estrategias que optimicen la comunicación usuario estudiante, teniendo en cuenta que el Paraguay es un país bilingüe y la Constitución Nacional lo coloca a ambos idiomas en el mismo nivel de importancia.
      El estudio fue gratuito y los datos obtenidos fueron  utilizados exclusivamente con la finalidad de los objetivos propuestos.
      Se dio justa participación a todos los estudiantes que  lo querían hacer libremente. Se consideró  justo realizar el estudio, pues con ello se representan datos muy útiles sobre las necesidades manifiestas  de los estudiantes con relación a la dificultad o complacencia que presentan en la cotidianeidad en la comunicación con el usuario guaraní hablante.


RESULTADOS
Del total de estudiantes del Instituto Dr. Andrés Barbero, de las carreras de Enfermería y de Obstetricia participaron del estudio el 54% (334). Mayoritariamente de sexo femenino, grupo etareo predominante de 21 a 24 años, de estado civil soltero/a, de la carrera de Enfermería y provenientes del Gran Asunción. El 54% de los/as  estudiantes de las carreras de Enfermería y de Obstetricia  usan poco el idioma guaraní, 31% usa mucho el idioma guaraní en la  comunicación y 15% manifiesta no hablar el idioma guaraní. El 94% de los estudiantes de las carreras de Enfermería y Obstetricia manifestaron tener un dominio bueno del  idioma guaraní.

Interpretación 1.   El 80% de los estudiantes marcaron la opción correcta: en esta posición descansa mejor mi pierna, 10% en esta posición descansa mejor mi cuerpo, 6% en esta posición descanso mejor, 3% en esta posición respiro mejor y 1% no responde.

Interpretación 2.  El 68% de los estudiantes marcaron la opción correcta: que la sangre circula mejor y hace que  descanse mi cuerpo, 11% que la sangre circula mejor por  mi cuerpo, 10% que la sangre que circula me descansa el cuerpo, 7% no responde y 4% que puedo correr y descansa mi cuerpo.

Interpretación 3. El 34% de los estudiantes marcaron: me duele el alma, 32% me duele la faringe (opción correcta), 20% me duele la garganta, 10% no responde y 4% me duele la laringe.

Interpretación 4. El 60% de las estudiantes marcaron la opción correcta: Sensación de tener la lengua porosa y no siento lo que como, 27% mi lengua es porosa y no siento lo que como, 6% mi lengua es como la pava y no es rico lo que como, 5% mi lengua es porosa y no es rica la comida que como, 2% no responde.

Interpretación 5. El 80% de los estudiantes marcaron la opción correcta: Me pica cuando orino además emana sangre, 7% me pica cuando orino además emana pus, 5% me molesta cuando orino porque sangra, 5% me pica cuando orino y 5% no responde.

	En cuanto al conocimiento  de términos médicos, el 73%  de los estudiantes presentaron de 5 a 6 respuestas correctas, 15% de 7 a 8 respuestas correctas, 10% 1 a 4 respuestas correctas y 2% no responde.
	En cuanto a la traducción de oraciones del castellano al guaraní, 40% presentó 4 respuestas correctas, 30% 3 respuestas correctas, 20% 2 respuestas correctas, 6% 1 respuesta correcta  y 4% no responde. 
	Respecto a la traducción del guaraní al castellano,  44% de los estudiantes presentaron 4 respuestas correctas, 28% 3 respuestas correctas, 9% 2 correctas, 11% 1 correcta y 8% no responde.
	En cuanto a la necesidad de conocer los vocablos folklóricos relacionados a términos médicos como Kambyrujere, pyaruru, ojeo. 59% de los estudiantes dijeron que es necesario para saber cómo el pueblo designa las enfermedades o males que le aqueja, 12% por necesidad psicológica y para no confrontar culturas,  11% para traducir correctamente y 10% sumergirse en ellas y desde esa óptica revertir conocimientos, 8% no responde.
	El 79%  de los estudiantes respondieron: me alegra y me llena de orgullo, 10% me es indiferente, 5% me desagrada y 6% no responde.
	Respecto a la importancia del uso del idioma guaraní, el 80%  de los estudiantes manifestaron  que es necesario para el entendimiento del usuario guaraní hablante y el prestador de salud, 12% se puede planear estrategias que no se quiere dar a conocer a extraños, 4% no es muy importante, se puede planear estrategias igual en castellano y 4% no responde.
	En relación a la valoración que atribuyen los estudiantes  al uso del idioma guaraní, 51% refirió ser una estrategia útil en Salud Pública, 24% fundamental para comunicarse con todos los paraguayos, 20% que es un patrimonio cultural intangible y 6% no responde.
	En cuanto al sentimiento expresado por los estudiantes  hacia el idioma guaraní, el 43% refiere de libertad, 37% confianza, 10% otros (orgullo, confianza, libertad, seguridad, familiarizado, placer, sentido de pertenencia), 6% no responde y 4% vergüenza (no por el idioma mismo, sino por  no saber hablar y por temor al ridículo, no es que rechace el idioma).
	Respecto a la inclusión del idioma guaraní dentro de la malla curricular de  las carreras de Enfermería y de Obstetricia, el 84% de los estudiantes consideran necesaria la inclusión, "nuestro  país es bilingüe y la lengua guaraní es un tesoro al que se debe apreciar en su justo valor. Como universidad de referencia, es nuestro deber apoyar y fomentar lo nacional, además es muy importante en nuestra carrera puesto que es una de las principales formas de comunicación con el usuario.
	Al relacionar el nivel de escolaridad de la carrera de Enfermería y el uso del idioma guaraní, el 20% de los estudiantes del 1° año,  usa mucho el idioma guaraní, 58% usa poco y 22% nada. 32% de los estudiantes del 2° año de la carrera de Enfermería usa mucho el idioma guaraní en su intercomunicación con el usuario guaraní hablante, 50% usa poco y 18% nada. 27% de los estudiantes del 3° año de la carrera de enfermería usan mucho el idioma guaraní, 43% usan poco en la intercomunicación con el usuario guaraní hablante  y 30% no usa nada en su comunicación. 25% de los estudiantes del 4° año usan mucho el idioma guaraní en su comunicación con el usuario guaraní hablante, 58% usa poco y 17% nada.
	Al relacionar el nivel de escolaridad de la carrera de Obstetricia  y el uso del idioma guaraní, el 29% de los estudiantes del 2° año usan mucho el idioma guaraní en la comunicación con el usuario guaraní hablante, 51% usa poco y el 20% nada. El  28% de los estudiantes del 3° año usan mucho el idioma guaraní, 55% usa poco en la intercomunicación con el usuario guaraní hablante y 17% nada. El  32% de los estudiantes del 4° año  usan mucho el idioma guaraní, 44% usa poco y 24% no usa nada el idioma guaraní  en su comunicación  con las usuarias guaraní hablantes.
	De 334 estudiantes se encuentran entre excelente y muy bueno, el 53/242 (22%) provenientes de Asunción y Gran Asunción, pero el 46/89 (52%) de los estudiantes de otras localidades con una p<0.00001, muy significativo,  por el origen de los estudiantes.
	El dominio del idioma guaraní de Muy bueno a Excelente es del 31% (101/334), Aceptable y Bueno en el 58% (191/334) y deficiente en el 11% (39/334) sin tener en cuenta la procedencia de los estudiantes.
	De la sumatoria de los % de la interpretación 1, interpretación 2, interpretación 3,  interpretación 4, interpretación 5 y dividido por 5, resulta un 64% que da como resultado un conocimiento  aceptable del idioma guaraní, teniendo en cuenta la escala del 60%. 
	El 73% de los estudiantes en cuanto a términos médicos tradujeron correctamente entre 5 a 6 palabras que da como resultado un conocimiento  bueno acerca de dichos términos. 
	De la sumatoria de los % de 4 y 3 respuestas traducidas correctamente del castellano al guaraní por los estudiantes, da un resultado del 70%, conocimiento aceptable.
	El 72% de los estudiantes tradujeron correctamente entre 3 y 4 oraciones del guaraní al castellano dando como resultado un conocimiento bueno.
	Teniendo en cuenta que el conocimiento de los estudiantes de las carreras de Enfermería y de Obstetricia  a través de  la interpretación de oraciones es aceptable, en la traducción del castellano al guaraní  aceptable, del guaraní al castellano bueno,  se concluye que  el grado de conocimiento es aceptable.
	El dominio que poseen los estudiantes del idioma guaraní de Muy bueno a Excelente es del 31% (101/334), Aceptable y Bueno en el 58% (191/334) y deficiente en el 11% (39/334) sin tener en cuenta la procedencia de los estudiantes.
	Teniendo en cuenta la escala del 60%, el resultado relacionado al dominio del idioma guaraní  de los estudiantes de las carreras de Enfermería y de Obstetricia es deficiente.

DISCUSIÓN
Desde la percepción de los estudiantes de las carreras de Enfermería y de Obstetricia  el 54% habla poco el idioma guaraní en la comunicación, 31% habla mucho y 15% no habla el idioma guaraní. Solamente el 22% de los estudiantes provenientes de Asunción y Gran Asunción presentan un dominio  del idioma guaraní de muy bueno a excelente. Sin embargo  un  94% de los estudiantes  califican  como bueno el dominio que poseen sobre el idioma guaraní, porque les permite mínimamente entender el mensaje recibido.
	Según los Dres.Villagra Marshall y Tadeo Zarratea, solamente hay un 27% de paraguayos que son de habla guaraní exclusiva, son monolingües, no hablan español. 9 a 10% que solo habla castellano y el resto, la mayoría inmensa, es bilingüe. Pero es un bilingüismo que uno no sabe -según las personas- si tiene mayor carga en guaraní o en castellano. Es un bilingüismo desperdigado, multiforme, hay gente que es más competente en castellano y otra que lo es en guaraní. Lo que necesitamos es que el paraguayo de mañana sea competente por igual en ambas lenguas, que maneje bien los dos códigos lingüísticos.
      Según la Dirección General de Estadísticas, Encuestas y Censo ( DGEEC) del 2002, existen 1.399.220 guaraní hablantes; 1.721.200 guaraní bilingües y 1.330.810 castellano bilingües". Sin embargo el último censo llevado a cabo por la DGEEC en el año 2012 menciona que hubo un descenso del monolingüe guaraní hablante en un 10%, pero pese a ello, los resultados parciales del censo, también indican que el guaraní sigue siendo el idioma más hablado en el Paraguay, aludiendo a un 77% de la población.
      La tendencia en la disminución del uso del idioma parece aumentar, ya que los actuales resultados, si bien son parciales, indican que sólo un 7,93% de la población se mantiene como monolingüe guaraní.
      Esto tal vez explique el resultado hallado en  este trabajo de investigación,  donde   aproximadamente 7 de cada 10 estudiantes hablan poco o no hablan nada el idioma guaraní.
      En cuanto al conocimiento demostrado por los estudiantes a través de  la interpretación del idioma guaraní en las traducciones del guaraní al castellano y del castellano al guaraní,  los estudiantes de las carreras de Enfermería y de Obstetricia  en su conjunto presentan  una calificación  aceptable.
      Según el Dr. Ramón Silva, el idioma guaraní puede desaparecer en dos generaciones, porque ya no es hablado por los niños en los hogares, indicó que los niños solo aprenden a hablar y escribir en la escuelas, pero el guaraní debe ser hablado, porque siempre fue así, a lo que el Dr. David Galeano refuto mencionando cuanto sigue: es difícil eso de creer, partiendo de la base de la cantidad de personas que todavía hablan el idioma. Se estima que,  más de 5.820.000 personas hablan el guaraní en el país, unos 2.680.000 son monolinguistas (hablan solo el guaraní). A esto hay que agregarle un estudio que revela que en el Mercosur alrededor de 9.000.000 de personas dependen en gran medida del idioma nativo.
      Para que una lengua se encuentre en peligro de extinción debe ser hablada por unas 100.000 personas, según un estudio francés, mencionó el Dr. Galeano. En lo que respecta al ámbito académico, antes que acabarse, se enseña en la Universidad de San Pablo, en Washington, Francia e Italia por dar algunos ejemplos."
      La docente de primaria y comunicadora Verónica Rodríguez dice: Es muy difícil que desaparezca en dos o tres generaciones, si bien ha aumentado los monolingües del castellano, todavía existe una fuerte dependencia del guaraní, sobre todo en regiones rurales como Caazapá, San Pedro, Caaguazú y otros Departamentos. Estos docentes coinciden en que la metodología utilizada en la enseñanza del idioma guaraní en las escuelas si puede repercutir negativamente en la sobrevivencia del guaraní.
      El  párrafo anterior coincide con la descripción del problema de este trabajo de investigación en que menciona que la Didáctica ineficiente en la enseñanza del idioma guaraní lleva al rechazo del uso del idioma guaraní por parte de los estudiantes, produce dificultad en la comprensión del mensaje recibido por parte del estudiante de enfermería y viceversa; además de la consiguiente dificultad para entablar una conversación fluida con el usuario guaraní hablante.
      A pesar de las opiniones de algunos docentes, el Ministerio de Educación y Cultura (MEC), considera que el guaraní está en expansión. La Directora General de Curriculum y Evaluación del Ministerio de Educación y Cultura (MEC), Nancy Benítez, sostiene que "hoy se apuesta por el guaraní en la enseñanza oficial desde el nivel inicial. La misma, coincide con el Dr. David Galeano, en donde  destaca que "hoy el 37% es monolingüe hablante y el  50% es bilingüe, lo que da como resultado que el 87% de la población se comunica en lengua nativa".
      Manifestaciones de una estudiante encuestada "creo que el guaraní se aprende en el entorno, en la familia,  y sí como apoyo la enseñanza del idioma  en la primaria y secundaria, y que no hablan por un tabú existente y no  por falta de enseñanza". En parte coincide con lo referido por el Prof. Ramón Silva que dice que el idioma guaraní se aprende a hablar  en el seno familiar, que posteriormente  se lee y se escribe en la escuela.
	En cuanto a la necesidad de conocer los vocablos folklóricos relacionados a términos médicos como Kambyrujere, py,aruru, ojeo, dijeron que es necesario para saber cómo el pueblo designa las enfermedades o males que le aqueja, por necesidad psicológica y para no confrontar culturas, para traducir correctamente, y sumergirse en ellas y desde esa óptica revertir conocimientos.
      Según el Prof. Dr. Dionisio González Torres en su libro El folklore del Paraguay menciona cuanto sigue: El conocimiento del folklore interesa a  todos los que tengan que trabajar en el campo y con la gente del pueblo y a los que, en las ciudades, deban tratar con ella. En estas circunstancias es necesario conocer cómo piensa y siente nuestro pueblo, cuáles son sus creencias, supersticiones, preconceptos, costumbres, tradiciones, etc. Eso facilitará la labor del que debe tratar con nuestra gente humilde, del pueblo y le será más fácil triunfar en ese medio y ayudar mejor a ella a resolver sus problemas.
      Los que ejercen la medicina y las ciencias paramédicas (enfermeras, obstetras, dietistas, etc.); los educadores en general, agrónomos y veterinarios, el sacerdote, el abogado, el militar, el policía, en fin, todas los profesionales pueden beneficiarse mucho con el conocimiento de nuestro folklore, para tener éxito en la profesión o empleo.
	Un error que frecuentemente cometen los profesionales al tratar con nuestra gente del pueblo es querer contraponer su cultura académica a lo que el pueblo sabe, con aire de superioridad o despectivo, rechazando todo lo que sea de origen vulgar, pueblerino, poniendo la etiqueta o sello de ignorancia y superstición a todas sus creencias.
      Profesionales de la salud en Catalunya presentaron un proyecto relacionado  a palabras de uso corriente en el ámbito sanitario y en el idioma de los inmigrantes de manera a disminuir dicha brecha comunicacional.  El idioma puede ser en muchos casos una barrera difícil de franquear en la comunicación entre el paciente y el profesional sanitario. En segundo lugar, la lengua no es la única dificultad que se interpone en la comunicación entre ambos: aun en los casos en los que haya un idioma común, las diferencias culturales pueden suponer un problema en la interacción entre las dos personas. Muy a menudo puede  encontrarse situaciones en las que tanto el profesional sanitario como el paciente no sean capaces de hablar con soltura otras lenguas.
      Respecto a la importancia del idioma guaraní, mayoritariamente manifestaron  que es necesario para el entendimiento del usuario guaraní hablante y el prestador de salud.
	Los estudiantes  mencionaron cuanto sigue: En p lugar, nuestro  país es bilingüe y la lengua guaraní es un tesoro al que se debe apreciar en su justo valor. Como universidad de referencia, es nuestro deber apoyar y fomentar lo nacional, y además es muy importante en nuestra carrera puesto que es una de las principales formas de comunicación con el usuario.
	Con relación a esto La Ley 28/92 en su artículo 1 dispone: Es obligatoria la enseñanza de las lenguas oficiales, Castellano y Guaraní, en todos los niveles del sistema educativo paraguayo: primario, secundario y universitario.
      Al trabajar  con personas  necesitamos los conocimientos del guaraní para una mejor comunicación, ya que   nosotros estamos más en contacto con personas provenientes del interior, quienes utilizan sólo el idioma guaraní, si una licenciado/a en Enfermería no conoce el idioma o no sabe expresar lo que tiene o siente  el paciente entonces como informaríamos, y esto representaría  una pérdida de acercamiento con el usuario. 
	En relación a la valoración  del uso del idioma guaraní, mayoritariamente coincidieron ser una estrategia útil en Salud Pública,  fundamental para comunicarse con todos los paraguayos,  y que es un patrimonio cultural intangible.
	El guaraní, idioma nacional, medio de comunicación y socialización por excelencia. Hasta hoy, según lo revelan los censos, buena parte de la población paraguaya habla exclusivamente el idioma guaraní. Lengua ágrafa por excelencia, sus hablantes trasmiten oralmente su literatura.
      Es fundamental que los/as estudiantes sepan aplicar los conocimientos adquiridos en los cursos anteriores, pues como profesionales, tendrán la necesidad de interpretar la actividad humana, por lo tanto, es importante que tengan claro que no solamente es necesario el estudio de la lengua en relación a la sociedad, o conocer como expresión de la cultura, o para describir a la sociedad en su forma de comunicación, sino es indispensable que los/as estudiantes tengan a la lengua guaraní como herramienta para expresar la comprensión de la misma sociedad Paraguaya.
	Algunos estudiantes  encuestados señalaron de esta manera la valoración del idioma guaraní: Es necesario para poder desenvolverse en el ámbito hospitalario. Ayuda al estudiante a que pueda manejarse adecuadamente con todos los usuarios y así evitar interpretaciones equivocadas de ambas partes. Porque  somos paraguayos y por ende debemos saber, conocer y con más razón en la carrera de enfermería puesto que estamos en contacto con personas de distintos niveles sociales y porque mejora la comunicación". Así como lo mencionó el Dr. Dionisio González Torres justificando su necesidad en las carreras de las Ciencias de la Salud.
	En cuanto al sentimiento expresado hacia el idioma guaraní, en su mayoría mencionaron de libertad, confianza, otros (orgullo, confianza, libertad, seguridad, familiarizado, placer, sentido de pertenencia), y un pequeño porcentaje indicó vergüenza (no por el idioma mismo, no es que rechace el idioma, sino por  no saber hablar y por temor al ridículo).
      Una de los encuestados respondió cuanto sigue: "No hablo tanto porque  me incomoda no saber hablar en público y entablar comunicación con el usuario."  En cuanto a otro encuestado: ". alegría y felicidad ya que tenemos dos idiomas oficiales. Porque muchos no saben comunicarse con el usuario y al usuario le dificulta comunicarse con nosotros que somos los prestadores de salud. Confianza, porque  sé que de esta manera puedo llegar mejor a mi paciente."
      Vergüenza porque  me cuesta, se ríen de mí. Sentimiento de inseguridad y preocupación debido a que no sea comprendida y no ser capaz de comprender las necesidades del usuario. En este caso se produce lo que se llama "la evitación", es una situación de baja autoestima en el manejo de la lengua. Se produce como un acto inhibitorio, en el que el hablante deja de producir el habla o el escrito para evitar cometer errores. Esto conduce a un empobrecimiento de la comunicación, puesto que el hablante, con el fin de evitarse problemas en el uso de la lengua o de cometer errores, renuncia a abordar determinados temas.
      Respecto a la inclusión del idioma guaraní dentro de la malla curricular de  las carreras de Enfermería y de Obstetricia, 84% considera necesaria la inclusión, Nuestro  país es bilingüe y la lengua guaraní es un tesoro al que se debe apreciar en su justo valor. Como universidad de referencia, es nuestro deber apoyar y fomentar lo nacional, además es muy importante en nuestra carrera puesto que es una de las principales formas de comunicación con el usuario. Me gustaría que haya una materia complementaria de guaraní, un guaraní comunicacional, que nos enseñe lo necesario para comunicarnos con el usuario guaraní hablante, porque la verdad  que nos dificulta mucho relacionarnos con el usuario.
      Muchas personas hablan solamente el idioma guaraní y es importante que nosotras/os como profesionales entendamos y podamos  comunicarnos con las personas. No todos conocemos el guaraní y los que conocemos sabemos poco o no sabemos expresarnos.
      La Universidad Nacional de Itapúa implementa la enseñanza del idioma guaraní movido por  un deseo de ampliar la oferta académica en un compromiso con la sociedad. Para estudiantes de antropología, Trabajadores sociales y trabajadores de  salud, entre otros, el conocimiento de esta lengua es un apoyo importante para su dinámica laboral.
 	Es una forma de dar confianza al usuario cuando conocemos y hablamos el mismo idioma, por lo tanto es una necesidad la inclusión. Como paraguayos/as, debemos estudiar y practicar el idioma guaraní y más aún para lograr una buena comunicación con el usuario que conoce el idioma y sólo se comunica en ese idioma. Porque ayudaría mucho para que los estudiantes al estar en contacto con los usuarios comprendan lo que ellos les están comunicando.
      Abogo por la inclusión del idioma guaraní en la malla curricular,  me siento más comprometida  siendo que doy atención integral  y debo eliminar barreras,  porque  es necesario el manejo del idioma guaraní para brindar atención integral.  Porque en la práctica y en el campo laboral es sumamente importante manejar este idioma tanto para entender a nuestras pacientes como para hacernos entender y que nuestras orientaciones y enseñanzas  sean completamente comprendidas.
      Vamos a trabajar con distintas personas de diferentes ciudades y compañías que hablan más guaraní que castellano, por eso es muy necesaria la inclusión de la enseñanza del idioma  guaraní.
      Es importante la inclusión del idioma guaraní en la malla curricular porque tendríamos más conocimiento del idioma  y podríamos comunicarnos mejor con los usuarios y lograr una buena comunicación  en cualquier parte de nuestro país ya que en muchos lugares solo se habla en guaraní. Porque el idioma es el nexo fundamental para el buen relacionamiento y entendimiento con los pacientes sobre todo aquellos que son monolingüe  guaraní hablante.

CONCLUSIÓN
El objetivo de esta investigación es evaluar el grado de conocimiento y el uso del idioma guaraní de  los estudiantes de las carreras de  Enfermería  y de Obstetricia  en  la interrelación con el  usuario guaraní hablante, del Instituto Dr. Andrés Barbero. Casa Central.
	Los hallazgos muestran que los estudiantes en gran porcentaje son  de sexo femenino, de 21 a 24 años de edad,  estado civil soltero/a, de la carrera de Enfermería y provenientes del Gran Asunción. 
	Los estudiantes de las carreras de Enfermería y de Obstetricia mayoritariamente hablan poco o no hablan el idioma guaraní, una minoría manifestó que utiliza mucho el idioma en su comunicación.
	Respecto al dominio que poseen sobre el idioma guaraní, manifestaron ser  bueno, lo suficiente para comunicarse.
	El conocimiento del idioma guaraní   en la comunicación con el usuario guaraní hablante de  los estudiantes, a través de la interpretación y traducción de oraciones tanto del castellano al guaraní y viceversa es aceptable.
	En cuanto a la necesidad de conocer los vocablos folklóricos relacionados a términos médicos,  mayoritariamente manifestaron ser  necesario para saber cómo el pueblo designa las enfermedades o males que le aqueja, por necesidad psicológica y para no confrontar culturas.
	Respecto a la importancia del idioma guaraní, en su mayoría revelaron que es necesario para el entendimiento del usuario guaraní hablante y el prestador de salud, relacionado a la valoración del uso del idioma guaraní refirieron ser una estrategia útil para la Salud Pública, fundamental para comunicarse entre todos los paraguayos.
	En cuanto al sentimiento expresado hacia el idioma guaraní, lo manifestaron de diversa manera, libertad, confianza, orgullo, seguridad, familiarizado, placer, sentido de pertenencia entre otros. 
	Mayoritariamente consideran necesaria la inclusión del idioma guaraní dentro de la malla curricular de  las carreras de Enfermería y de Obstetricia.
	Al  relacionar   escolaridad y uso del idioma, independientemente del año cursado y carrera, una minoría usa mucho el idioma guaraní en su interrelación comunicacional.
	Relacionado la procedencia y el dominio del idioma guaraní se encuentra una minoría de estudiantes provenientes de Asunción y Gran Asunción con dominio entre Excelente y Muy Bueno,  contra estudiantes provenientes de otras localidades con  una p<0.00001, muy significativo,  por el origen de los estudiantes.
      Con lo que se concluye que el grado de conocimiento del idioma guaraní de los estudiantes de las carreras de Enfermería y de Obstetricia del Instituto Dr. Andrés Barbero, Casa Central,  es aceptable y el uso deficiente en la interrelación con el usuario guaraní hablante. 

RECOMENDACIONES
Al Instituto Dr. Andrés Barbero

* Gerenciar el desarrollo de  seminarios talleres  sobre el idioma  guaraní para los estudiantes de las carreras de Enfermería y de Obstetricia con la finalidad de hacer uso eficiente del idioma en la comunicación con el individuo, la familia y la comunidad para el logro de la  atención integral. 
* Introducir en la malla curricular de las carreras de Enfermería y de Obstetricia un guaraní comunicacional que les proporcione las herramientas básicas con terminologías propias de las ciencias de la salud.

A los centros de estudiantes de Enfermería y de Obstetricia
* Organizar jornadas de comunicación oral y escrita con ayuda de conocidos docentes guaraniólogos de la casa de estudios, de manera a lograr la  competencia  en la comunicación con el usuario guaraní hablante.  




Trabajos Citados
---. "Constitución Nacional: Ley Nº 4.251: De Lenguas". Asunción: Editorial Litocolor; 2010. Impreso.
---. Aula Intercultural: El Portal de la Educación Intercultural. Madrid: Federación de Trabajadores de la Enseñanza - Unión General de Trabajadores (FETE-UGT); 2003/10 de mayo de 2013. Internet. 03 de julio de 2013.
---. Campaña Nacional de Interculturalidad: "Habla en tu idioma, es tu derecho". Aula Intercultural: El Portal de la Educación Intercultural, 2003/10 de mayo de 2013. Internet. 03 de julio de 2013.
---. Dirección General de Estadística, Encuestas y Censos. Censo 2002. DGEEC, 2002. Internet. 10 de octubre de 2012.
---. El Bilingüismo en Paraguay, ¿Una Realidad Posible? "Ha.Che retâ Paraguay." Fernández J, editor; 2011. 03 de junio de 2011. Internet.
---. El Guaraní es una Lengua Descriptiva: Hablando en Guaraní la Cura y el Tratamiento es Seguro. Instituto de Previsión Social. Asunción: IPS, 2003. Internet. 10 de octubre de 2012.
---. El Idioma Guaraní y la Realidad Multicultural del Mercosur. Portal Guarani.com, 2010/17 de mayo 2013. Internet. 22 de Octubre  de 2012.
---. Enseñanza del Guaraní para la Universidad Nacional de Formosa. Universidad Nacional de Itapúa. Itapúa: UNI, 21 de febrero de 2013. Internet. 10 de octubre de 2013.
---. Estudiantil. Abc Color. 17 de abril de 2009/20 de abril de 2009. Internet. 10 de octubre de 2012.
---. Guarani Ñe`ê. Centro de Estudiantes de Medicina de la Universidad Católica (CEMUCA); 2011. Internet.
---. La Educación Bilingüe y la Interculturalidad en América Latina: El Significado y la Importancia de la Interculturalidad. Århus Universitet. Trine: Århus Universitet; 2003. Internet.
---. Ministerio de Educación y Cultura. "Modelo Nacional de Acreditación de la Educación Superior". Asunción : MEC ; 2009.p. pág. 9. Impreso.
---. Paraguay: Idioma Guaraní, Hoy. Centro de Documentación Mapuche. Montevideo: Centro de Documentación Mapuche; 16 de agosto de 2003. Internet. 10 de octubre de 2013.
---. Programa de estudio de Guaraní III. Universidad Nacional de Asunción, Facultad de Derecho y Ciencias Sociales, Escuela de Ciencias Sociales y Políticas.Asunción. 2012. Impreso. 
---. Programa de las Naciones Unidas.  "Diálogos sobre identidad y diversidad cultural en el Paraguay".  Asunción: PNUD; 2004. p. 66. Impreso.
---. Recursos Humanos, Concurso Público de Oposición de Méritos y Aptitudes Resultado: Dirección General. Ministerio de Salud Pública y Bienestar Social. Internet. 24 de agosto de 2013.
---. Se Debe Dejar el Guaraní Artificioso de Palabras Inventadas. Abc Color, 07 de abril de 2012/20 de abril de 2012. Internet. 10 de octubre de 2012.
---. Se Enseñan Idiomas Quechua, Guaraní y Qom. Universidad Nacional del Rosario. CLEC; 07 de abril de 2011. Internet. 10 de octubre de 2013.
---. Telesurtv.net. Lima: Telesur. Internet. 10 de octubre de 2013.
---. Un 10% de los Paraguayos Dejó de Hablar Guaraní, Según Censo 2012 . Ultima Hora.com. Asunción, 21 de Diciembre de 2012. Internet. 10 de octubre de 2012.
---. Vicisitudes del Uso y Enseñanza del Guaraní. Portal Guarani.com. Asunción: Portal Guarani; 2012. Internet. 10 de julio de 2012.
Benítez, TG de. "La Lengua Materna como Facilitadora de la Producción Escrita en la Segunda Lengua". Biblioteca Paraguaya de Antropología. Asunción. 2012; Vol. 82. 185 p. Impreso.
Caballero M, et al. Programa Emblemático Gubernamental: Unidades de Salud de la Familia: Informe de Evaluación de Proceso. Asunción: Ministerio de Hacienda; 2010. Internet.
Colmán, NR. "Ñande îpî cuéra (Nuestros Antepasados)". Poema Etnogenético y Mitológico: Protohistoria de la Raza Guaraní. Asunción: El Lector; 2009. Impreso.
Corvalan G y G. de Granda. "Sociedad y Lengua: Bilingüismo en el Paraguay". Asunción: Centro Paraguayo de Estudios Sociológicos; 1982. Impreso.
Galeano Oliveira D, y DM González Torres Vicisitudes del Uso y Enseñanza del Guaraní. Rede Social Café Historia, 06 de mayo 2010/03 de junio 2011. Internet. 06 de julio de 2011.
González, R. "Debate Sobre Vida Útil del Guaraní Genera Polémica Entre Académicos". Diario Última Hora. Domingo 16 de setiembre de 2012; p 16. Impreso.
González, Torres DM. "Folklore del Paraguay". Asunción: Servilibro; 2007.p. 602 p. Impreso.
Meliá B. "Una Nación, Dos Culturas." Asunción: RP ediciones; 1990. p. 38-49; 69-77. Impreso.
Rodrígues, JM. Diversidad, Interculturalidad y Educación en el Brasil y en Paraguay. Asunción: CEADUC; 2010. 20 de abril de 2011. Internet.
Vera, H. "En Busca del Hueso perdido". Asunción: Servilibro; 2012. Impreso.
Zarratea, Tadeo. "La Diversidad Lingüística en América. De México al Cono Sur". Amarauna: UNESCO Etxea; 2007. Impreso.
Zarratea, Tadeo. "Lenguas de América IV Foro de las Lenguas Amerindias". Catalunya : Casa América Catalunya; 2007. Impreso.

Maidana 5



