---
title: "Modos de afrontamiento al estrés por profesionales del área de Enfermería de Ciudad del Este que desempeñan roles en diferentes ámbitos"
author: "Gladys Isabel Aranda Moreno^[Facultad de Medicina, Universidad del Norte], Nelson Santander^[Facultad de Medicina, Universidad del Norte]"
output: 
  html_document: 
    keep_md: yes
---

```{r echo=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
library(ggplot2)
library(readr)
```

# Resultados

```{r tbl1, fig.height=4, fig.width=8}
tbl1 <- read_csv("v06_02a01_tbl1.csv")

x <- factor(
  colnames(tbl1[-1]),
  levels = c("Casi siempre", "Frecuentemente", "Algunas veces", "Casi nunca", "No responde")
) 

gp <- function(q) {
  n <- q
  y <- as.numeric(tbl1[n, -1])
  t <- as.character(tbl1[n , 1])
  t <- paste0("Indicador No.", n, ": ", t)
  ggplot(data.frame(x, y), aes(x, y)) +
    geom_col() +
    geom_label(aes(label = y)) +
    labs(x = t, y = "") +
    theme_bw()
}

gp(1)
gp(2)
gp(3)
gp(4)
gp(5)
gp(6)
gp(7)
gp(8)
gp(9)
gp(10)
gp(11)
gp(12)
gp(13)
gp(14)
gp(15)
gp(16)
gp(17)
gp(18)
gp(19)
gp(20)
gp(21)
gp(22)
```

```{r plot2358, fig.height=4, fig.width=8}

gp <- function(y1, y2, t) {
  categoria <- factor(
    x = c(
      "Nunca",
      "Raras veces",
      "Algunas veces",
      "A menudo",
      "Con mucha frecuencia"
    ), ordered = TRUE,
    levels = c(
      "Nunca",
      "Raras veces",
      "Algunas veces",
      "A menudo",
      "Con mucha frecuencia"
    )
  )

  x <- rep(categoria, 2)
  y <- c(y1, y2)
  z <- rep(
    c("Grupo 1 (20-30 a??os)", "Grupo 2 (31-45 a??os"),
    5
  )

    df <- data.frame(x, y, z)

  g <- ggplot(df, aes(x, y)) +
    geom_bar(
      aes(fill = factor(z)),
      stat = "identity",
      position = "dodge"
    ) +
    geom_label(
      aes(label = y, group = factor(z)),
      vjust = 0.5,
      position = position_dodge(0.9),
      color = "black"
    ) +
    theme_bw() +
    theme(
      legend.position = "bottom",
      legend.title = element_blank()
    ) +
    scale_fill_grey(end = 0.6)
  
  print(g)
    
}

t <- "Indicador 'Hablar con otros para saber lo que ellos harían'"
y1 <- c(1,15,23,29,32)
y2 <- c(1,3,17,20,59)

gp(y1, y2, t)

```

